export const iconsDataGuangfa = [
  {
    id: 0,
    name: "gfaom-BGDW",
    alias: [],
    componentName: "IconGfaomBGDW",
    componentAlias: [],
    title: "高分辨率海洋生物地理数据",
    category: "Oceanography",
    categoryCN: "海洋学",
    author: "KSW",
    tag: ["海洋生物", "地理数据", "高分辨率"],
    projectName: "guangfa",
    modifiedTime: "2024-11-15T10:08:15.693Z",
  },
  {
    id: 1,
    name: "gfaom-BGFX",
    alias: [],
    componentName: "IconGfaomBGFX",
    componentAlias: [],
    title: "高分辨率图形渲染框架",
    category: "Graphics",
    categoryCN: "图形渲染",
    author: "KSW",
    tag: ["高分辨率", "图形渲染", "框架"],
    projectName: "guangfa",
    modifiedTime: "2024-11-15T10:06:08.004Z",
  },
  {
    id: 2,
    name: "gfaom-BGFY",
    alias: [],
    componentName: "IconGfaomBGFY",
    componentAlias: [],
    title: "高分辨率海洋生物地球化学模型",
    category: "Oceanography",
    categoryCN: "海洋学",
    author: "KSW",
    tag: ["海洋生物地球化学", "高分辨率模型", "海洋生态系统"],
    projectName: "guangfa",
    modifiedTime: "2024-11-15T10:06:08.009Z",
  },
  {
    id: 3,
    name: "gfaom-BGGK",
    alias: [],
    componentName: "IconGfaomBGGK",
    componentAlias: [],
    title: "广发 变更管控",
    category: "GF AOM",
    categoryCN: "广发 AOM",
    author: "KSW",
    tag: ["广发", "AOM", "变更"],
    projectName: "guangfa",
    modifiedTime: "2024-11-07T03:44:01.993Z",
  },
  {
    id: 4,
    name: "gfaom-BGGL",
    alias: [],
    componentName: "IconGfaomBGGL",
    componentAlias: [],
    title: "广发 变更管理",
    category: "GuangFa AOM",
    categoryCN: "广发 AOM",
    author: "KSW",
    tag: ["广发", "AOM", "变更"],
    projectName: "guangfa",
    modifiedTime: "2024-11-07T03:44:01.993Z",
  },
  {
    id: 5,
    name: "gfaom-BGSJ",
    alias: [],
    componentName: "IconGfaomBGSJ",
    componentAlias: [],
    title: "全球海洋观测系统",
    category: "Oceanography",
    categoryCN: "海洋学",
    author: "KSW",
    tag: ["海洋观测", "全球系统", "背景调查", "环境监测"],
    projectName: "guangfa",
    modifiedTime: "2024-11-15T10:06:08.018Z",
  },
  {
    id: 6,
    name: "gfaom-BSGZ",
    alias: [],
    componentName: "IconGfaomBSGZ",
    componentAlias: [],
    title: "高分辨率海洋生物地理信息系统",
    category: "Oceanography",
    categoryCN: "海洋学",
    author: "KSW",
    tag: ["海洋生物", "地理信息系统", "高分辨率", "数据处理"],
    projectName: "guangfa",
    modifiedTime: "2024-11-15T10:06:08.022Z",
  },
  {
    id: 7,
    name: "gfaom-CJDDGL",
    alias: [],
    componentName: "IconGfaomCJDDGL",
    componentAlias: [],
    title: "广发 采集调度管理",
    category: "GuangFa AOM",
    categoryCN: "广发 AOM",
    author: "KSW",
    tag: ["广发", "AOM", "采集", "调度"],
    projectName: "guangfa",
    modifiedTime: "2024-11-07T03:44:01.993Z",
  },
  {
    id: 8,
    name: "gfaom-GJGL",
    alias: [],
    componentName: "IconGfaomGJGL",
    componentAlias: [],
    title: "广发 工具管理",
    category: "GuangFa AOM",
    categoryCN: "广发 AOM",
    author: "KSW",
    tag: ["广发", "AOM", "工具", "管理"],
    projectName: "guangfa",
    modifiedTime: "2024-11-07T03:44:01.993Z",
  },
  {
    id: 9,
    name: "gfaom-parameter-configuration",
    alias: [],
    componentName: "IconGfaomParameterConfiguration",
    componentAlias: [],
    title: "",
    category: "Other",
    categoryCN: "其他",
    author: "KSW",
    tag: [],
    projectName: "guangfa",
    modifiedTime: "2025-01-08T03:03:46.000Z",
  },
  {
    id: 10,
    name: "gfaom-permissions",
    alias: [],
    componentName: "IconGfaomPermissions",
    componentAlias: [],
    title: "",
    category: "Other",
    categoryCN: "其他",
    author: "KSW",
    tag: [],
    projectName: "guangfa",
    modifiedTime: "2025-01-08T03:03:46.000Z",
  },
  {
    id: 11,
    name: "gfaom-QXGL",
    alias: [],
    componentName: "IconGfaomQXGL",
    componentAlias: [],
    title: "广发 权限管理",
    category: "GuangFa AOM",
    categoryCN: "广发 AOM",
    author: "KSW",
    tag: ["广发", "AOM", "权限", "管理"],
    projectName: "guangfa",
    modifiedTime: "2024-11-07T03:44:01.992Z",
  },
  {
    id: 12,
    name: "gfaom-setting-config",
    alias: [],
    componentName: "IconGfaomSettingConfig",
    componentAlias: [],
    title: "",
    category: "Other",
    categoryCN: "其他",
    author: "KSW",
    tag: [],
    projectName: "guangfa",
    modifiedTime: "2025-01-08T03:03:46.000Z",
  },
  {
    id: 13,
    name: "gfaom-SYKB",
    alias: [],
    componentName: "IconGfaomSYKB",
    componentAlias: [],
    title: "广发 首页看板",
    category: "GuangFa AOM",
    categoryCN: "广发 AOM",
    author: "KSW",
    tag: ["广发", "AOM", "看板"],
    projectName: "guangfa",
    modifiedTime: "2024-11-07T03:44:01.993Z",
  },
  {
    id: 14,
    name: "gfaom-task-list",
    alias: [],
    componentName: "IconGfaomTaskList",
    componentAlias: [],
    title: "",
    category: "Other",
    categoryCN: "其他",
    author: "KSW",
    tag: [],
    projectName: "guangfa",
    modifiedTime: "2025-01-08T03:03:46.000Z",
  },
  {
    id: 15,
    name: "gfaom-YHGL",
    alias: [],
    componentName: "IconGfaomYHGL",
    componentAlias: [],
    title: "广发 用户管理",
    category: "GuangFa AOM",
    categoryCN: "广发 AOM",
    author: "KSW",
    tag: ["广发", "AOM", "用户", "管理"],
    projectName: "guangfa",
    modifiedTime: "2024-11-07T03:44:01.992Z",
  },
];
