export const iconsDataKAPA = [
  {
    id: 0,
    name: "apa-agent-manage-fill",
    alias: [],
    componentName: "IconApaAgentManageFill",
    componentAlias: [],
    title: "",
    category: "KAPA",
    categoryCN: "KAPA",
    author: "KSW",
    tag: [],
    projectName: "KAPA",
    modifiedTime: "2025-08-06T09:13:57.791Z",
  },
  {
    id: 1,
    name: "apa-agent-manage",
    alias: [],
    componentName: "IconApaAgentManage",
    componentAlias: [],
    title: "",
    category: "KAPA",
    categoryCN: "KAPA",
    author: "KSW",
    tag: [],
    projectName: "KAPA",
    modifiedTime: "2025-08-06T09:13:57.792Z",
  },
  {
    id: 2,
    name: "apa-assoc",
    alias: [],
    componentName: "IconApaAssoc",
    componentAlias: [],
    title: "",
    category: "KAPA",
    categoryCN: "KAPA",
    author: "KSW",
    tag: [],
    projectName: "KAPA",
    modifiedTime: "2025-08-28T02:48:40.931Z",
  },
  {
    id: 3,
    name: "apa-attachment",
    alias: [],
    componentName: "IconApaAttachment",
    componentAlias: [],
    title: "",
    category: "KAPA",
    categoryCN: "KAPA",
    author: "KSW",
    tag: [],
    projectName: "KAPA",
    modifiedTime: "2025-10-13T03:25:37.962Z",
  },
  {
    id: 4,
    name: "apa-audio-color",
    alias: [],
    componentName: "IconApaAudioColor",
    componentAlias: [],
    title: "",
    category: "KAPA",
    categoryCN: "KAPA",
    author: "KSW",
    tag: [],
    projectName: "KAPA",
    modifiedTime: "2025-10-13T03:25:37.962Z",
  },
  {
    id: 5,
    name: "apa-book",
    alias: [],
    componentName: "IconApaBook",
    componentAlias: [],
    title: "",
    category: "KAPA",
    categoryCN: "KAPA",
    author: "KSW",
    tag: [],
    projectName: "KAPA",
    modifiedTime: "2025-08-15T02:26:32.716Z",
  },
  {
    id: 6,
    name: "apa-capsule-app",
    alias: [],
    componentName: "IconApaCapsuleApp",
    componentAlias: [],
    title: "",
    category: "KAPA",
    categoryCN: "KAPA",
    author: "KSW",
    tag: [],
    projectName: "KAPA",
    modifiedTime: "2025-11-13T06:15:00.914Z",
  },
  {
    id: 7,
    name: "apa-capsule",
    alias: [],
    componentName: "IconApaCapsule",
    componentAlias: [],
    title: "",
    category: "KAPA",
    categoryCN: "KAPA",
    author: "KSW",
    tag: [],
    projectName: "KAPA",
    modifiedTime: "2025-10-13T03:25:37.962Z",
  },
  {
    id: 8,
    name: "apa-clean-app",
    alias: [],
    componentName: "IconApaCleanApp",
    componentAlias: [],
    title: "",
    category: "KAPA",
    categoryCN: "KAPA",
    author: "KSW",
    tag: [],
    projectName: "KAPA",
    modifiedTime: "2025-11-13T06:15:00.915Z",
  },
  {
    id: 9,
    name: "apa-clean",
    alias: [],
    componentName: "IconApaClean",
    componentAlias: [],
    title: "",
    category: "KAPA",
    categoryCN: "KAPA",
    author: "KSW",
    tag: [],
    projectName: "KAPA",
    modifiedTime: "2025-08-28T02:48:40.931Z",
  },
  {
    id: 10,
    name: "apa-component",
    alias: [],
    componentName: "IconApaComponent",
    componentAlias: [],
    title: "",
    category: "KAPA",
    categoryCN: "KAPA",
    author: "KSW",
    tag: [],
    projectName: "KAPA",
    modifiedTime: "2025-07-30T02:08:30.009Z",
  },
  {
    id: 11,
    name: "apa-component2",
    alias: [],
    componentName: "IconApaComponent2",
    componentAlias: [],
    title: "",
    category: "KAPA",
    categoryCN: "KAPA",
    author: "KSW",
    tag: [],
    projectName: "KAPA",
    modifiedTime: "2025-08-06T09:13:57.792Z",
  },
  {
    id: 12,
    name: "apa-config-app",
    alias: [],
    componentName: "IconApaConfigApp",
    componentAlias: [],
    title: "",
    category: "KAPA",
    categoryCN: "KAPA",
    author: "KSW",
    tag: [],
    projectName: "KAPA",
    modifiedTime: "2025-11-13T06:15:00.915Z",
  },
  {
    id: 13,
    name: "apa-config",
    alias: [],
    componentName: "IconApaConfig",
    componentAlias: [],
    title: "",
    category: "KAPA",
    categoryCN: "KAPA",
    author: "KSW",
    tag: [],
    projectName: "KAPA",
    modifiedTime: "2025-08-28T02:48:19.045Z",
  },
  {
    id: 14,
    name: "apa-control",
    alias: [],
    componentName: "IconApaControl",
    componentAlias: [],
    title: "",
    category: "KAPA",
    categoryCN: "KAPA",
    author: "KSW",
    tag: [],
    projectName: "KAPA",
    modifiedTime: "2025-10-13T03:25:37.962Z",
  },
  {
    id: 15,
    name: "apa-copy-2",
    alias: [],
    componentName: "IconApaCopy2",
    componentAlias: [],
    title: "",
    category: "KAPA",
    categoryCN: "KAPA",
    author: "KSW",
    tag: [],
    projectName: "KAPA",
    modifiedTime: "2025-09-09T09:41:03.074Z",
  },
  {
    id: 16,
    name: "apa-copy-markdown",
    alias: [],
    componentName: "IconApaCopyMarkdown",
    componentAlias: [],
    title: "",
    category: "KAPA",
    categoryCN: "KAPA",
    author: "KSW",
    tag: [],
    projectName: "KAPA",
    modifiedTime: "2025-09-02T03:49:54.240Z",
  },
  {
    id: 17,
    name: "apa-copy",
    alias: [],
    componentName: "IconApaCopy",
    componentAlias: [],
    title: "",
    category: "KAPA",
    categoryCN: "KAPA",
    author: "KSW",
    tag: [],
    projectName: "KAPA",
    modifiedTime: "2025-08-28T02:48:19.067Z",
  },
  {
    id: 18,
    name: "apa-cue-word-color",
    alias: [],
    componentName: "IconApaCueWordColor",
    componentAlias: [],
    title: "",
    category: "KAPA",
    categoryCN: "KAPA",
    author: "KSW",
    tag: [],
    projectName: "KAPA",
    modifiedTime: "2025-09-09T09:41:03.074Z",
  },
  {
    id: 19,
    name: "apa-database",
    alias: [],
    componentName: "IconApaDatabase",
    componentAlias: [],
    title: "",
    category: "KAPA",
    categoryCN: "KAPA",
    author: "KSW",
    tag: [],
    projectName: "KAPA",
    modifiedTime: "2025-08-06T09:13:57.792Z",
  },
  {
    id: 20,
    name: "apa-date",
    alias: [],
    componentName: "IconApaDate",
    componentAlias: [],
    title: "",
    category: "KAPA",
    categoryCN: "KAPA",
    author: "KSW",
    tag: [],
    projectName: "KAPA",
    modifiedTime: "2025-08-28T02:48:40.931Z",
  },
  {
    id: 21,
    name: "apa-delete",
    alias: [],
    componentName: "IconApaDelete",
    componentAlias: [],
    title: "",
    category: "KAPA",
    categoryCN: "KAPA",
    author: "KSW",
    tag: [],
    projectName: "KAPA",
    modifiedTime: "2025-11-13T06:15:00.916Z",
  },
  {
    id: 22,
    name: "apa-desc",
    alias: [],
    componentName: "IconApaDesc",
    componentAlias: [],
    title: "",
    category: "KAPA",
    categoryCN: "KAPA",
    author: "KSW",
    tag: [],
    projectName: "KAPA",
    modifiedTime: "2025-08-28T02:48:40.932Z",
  },
  {
    id: 23,
    name: "apa-dislike-fill",
    alias: [],
    componentName: "IconApaDislikeFill",
    componentAlias: [],
    title: "",
    category: "KAPA",
    categoryCN: "KAPA",
    author: "KSW",
    tag: [],
    projectName: "KAPA",
    modifiedTime: "2025-08-28T02:48:19.077Z",
  },
  {
    id: 24,
    name: "apa-dislike",
    alias: [],
    componentName: "IconApaDislike",
    componentAlias: [],
    title: "",
    category: "KAPA",
    categoryCN: "KAPA",
    author: "KSW",
    tag: [],
    projectName: "KAPA",
    modifiedTime: "2025-08-28T02:48:19.091Z",
  },
  {
    id: 25,
    name: "apa-down",
    alias: [],
    componentName: "IconApaDown",
    componentAlias: [],
    title: "",
    category: "KAPA",
    categoryCN: "KAPA",
    author: "KSW",
    tag: [],
    projectName: "KAPA",
    modifiedTime: "2025-07-30T02:08:30.010Z",
  },
  {
    id: 26,
    name: "apa-edit",
    alias: [],
    componentName: "IconApaEdit",
    componentAlias: [],
    title: "",
    category: "KAPA",
    categoryCN: "KAPA",
    author: "KSW",
    tag: [],
    projectName: "KAPA",
    modifiedTime: "2025-08-15T02:26:32.716Z",
  },
  {
    id: 27,
    name: "apa-empower",
    alias: [],
    componentName: "IconApaEmpower",
    componentAlias: [],
    title: "",
    category: "KAPA",
    categoryCN: "KAPA",
    author: "KSW",
    tag: [],
    projectName: "KAPA",
    modifiedTime: "2025-09-12T11:02:29.095Z",
  },
  {
    id: 28,
    name: "apa-erase",
    alias: [],
    componentName: "IconApaErase",
    componentAlias: [],
    title: "",
    category: "KAPA",
    categoryCN: "KAPA",
    author: "KSW",
    tag: [],
    projectName: "KAPA",
    modifiedTime: "2025-10-13T03:25:37.963Z",
  },
  {
    id: 29,
    name: "apa-excel-color",
    alias: [],
    componentName: "IconApaExcelColor",
    componentAlias: [],
    title: "",
    category: "KAPA",
    categoryCN: "KAPA",
    author: "KSW",
    tag: [],
    projectName: "KAPA",
    modifiedTime: "2025-10-13T03:25:37.963Z",
  },
  {
    id: 30,
    name: "apa-exit-FS",
    alias: [],
    componentName: "IconApaExitFS",
    componentAlias: [],
    title: "",
    category: "KAPA",
    categoryCN: "KAPA",
    author: "KSW",
    tag: [],
    projectName: "KAPA",
    modifiedTime: "2025-10-13T03:25:37.963Z",
  },
  {
    id: 31,
    name: "apa-export",
    alias: [],
    componentName: "IconApaExport",
    componentAlias: [],
    title: "",
    category: "KAPA",
    categoryCN: "KAPA",
    author: "KSW",
    tag: [],
    projectName: "KAPA",
    modifiedTime: "2025-09-02T03:49:54.240Z",
  },
  {
    id: 32,
    name: "apa-eye",
    alias: [],
    componentName: "IconApaEye",
    componentAlias: [],
    title: "",
    category: "KAPA",
    categoryCN: "KAPA",
    author: "KSW",
    tag: [],
    projectName: "KAPA",
    modifiedTime: "2025-08-15T02:26:32.716Z",
  },
  {
    id: 33,
    name: "apa-failure",
    alias: [],
    componentName: "IconApaFailure",
    componentAlias: [],
    title: "",
    category: "KAPA",
    categoryCN: "KAPA",
    author: "KSW",
    tag: [],
    projectName: "KAPA",
    modifiedTime: "2025-11-13T06:15:00.916Z",
  },
  {
    id: 34,
    name: "apa-folder-open-color",
    alias: [],
    componentName: "IconApaFolderOpenColor",
    componentAlias: [],
    title: "",
    category: "KAPA",
    categoryCN: "KAPA",
    author: "KSW",
    tag: [],
    projectName: "KAPA",
    modifiedTime: "2025-11-13T06:15:00.917Z",
  },
  {
    id: 35,
    name: "apa-full-screen",
    alias: [],
    componentName: "IconApaFullScreen",
    componentAlias: [],
    title: "",
    category: "KAPA",
    categoryCN: "KAPA",
    author: "KSW",
    tag: [],
    projectName: "KAPA",
    modifiedTime: "2025-10-13T03:25:37.963Z",
  },
  {
    id: 36,
    name: "apa-go-agent",
    alias: [],
    componentName: "IconApaGoAgent",
    componentAlias: [],
    title: "",
    category: "KAPA",
    categoryCN: "KAPA",
    author: "KSW",
    tag: [],
    projectName: "KAPA",
    modifiedTime: "2025-09-09T09:41:03.074Z",
  },
  {
    id: 37,
    name: "apa-grip-vertical",
    alias: [],
    componentName: "IconApaGripVertical",
    componentAlias: [],
    title: "",
    category: "KAPA",
    categoryCN: "KAPA",
    author: "KSW",
    tag: [],
    projectName: "KAPA",
    modifiedTime: "2025-07-30T02:08:30.010Z",
  },
  {
    id: 38,
    name: "apa-hide",
    alias: [],
    componentName: "IconApaHide",
    componentAlias: [],
    title: "",
    category: "KAPA",
    categoryCN: "KAPA",
    author: "KSW",
    tag: [],
    projectName: "KAPA",
    modifiedTime: "2025-08-15T02:26:32.716Z",
  },
  {
    id: 39,
    name: "apa-hot-color",
    alias: [],
    componentName: "IconApaHotColor",
    componentAlias: [],
    title: "",
    category: "KAPA",
    categoryCN: "KAPA",
    author: "KSW",
    tag: [],
    projectName: "KAPA",
    modifiedTime: "2025-11-13T06:15:00.917Z",
  },
  {
    id: 40,
    name: "apa-HTTP",
    alias: [],
    componentName: "IconApaHTTP",
    componentAlias: [],
    title: "",
    category: "KAPA",
    categoryCN: "KAPA",
    author: "KSW",
    tag: [],
    projectName: "KAPA",
    modifiedTime: "2025-08-28T02:48:40.930Z",
  },
  {
    id: 41,
    name: "apa-image-color",
    alias: [],
    componentName: "IconApaImageColor",
    componentAlias: [],
    title: "",
    category: "KAPA",
    categoryCN: "KAPA",
    author: "KSW",
    tag: [],
    projectName: "KAPA",
    modifiedTime: "2025-10-13T03:25:37.963Z",
  },
  {
    id: 42,
    name: "apa-import",
    alias: [],
    componentName: "IconApaImport",
    componentAlias: [],
    title: "",
    category: "KAPA",
    categoryCN: "KAPA",
    author: "KSW",
    tag: [],
    projectName: "KAPA",
    modifiedTime: "2025-08-28T02:48:40.932Z",
  },
  {
    id: 43,
    name: "apa-increase-fill",
    alias: [],
    componentName: "IconApaIncreaseFill",
    componentAlias: [],
    title: "",
    category: "KAPA",
    categoryCN: "KAPA",
    author: "KSW",
    tag: [],
    projectName: "KAPA",
    modifiedTime: "2025-09-12T11:02:29.095Z",
  },
  {
    id: 44,
    name: "apa-increase",
    alias: [],
    componentName: "IconApaIncrease",
    componentAlias: [],
    title: "",
    category: "KAPA",
    categoryCN: "KAPA",
    author: "KSW",
    tag: [],
    projectName: "KAPA",
    modifiedTime: "2025-08-15T02:26:32.716Z",
  },
  {
    id: 45,
    name: "apa-invk",
    alias: [],
    componentName: "IconApaInvk",
    componentAlias: [],
    title: "",
    category: "KAPA",
    categoryCN: "KAPA",
    author: "KSW",
    tag: [],
    projectName: "KAPA",
    modifiedTime: "2025-08-28T02:48:40.932Z",
  },
  {
    id: 46,
    name: "apa-IP",
    alias: [],
    componentName: "IconApaIP",
    componentAlias: [],
    title: "",
    category: "KAPA",
    categoryCN: "KAPA",
    author: "KSW",
    tag: [],
    projectName: "KAPA",
    modifiedTime: "2025-09-02T03:49:54.240Z",
  },
  {
    id: 47,
    name: "apa-knowledge-base",
    alias: [],
    componentName: "IconApaKnowledgeBase",
    componentAlias: [],
    title: "",
    category: "KAPA",
    categoryCN: "KAPA",
    author: "KSW",
    tag: [],
    projectName: "KAPA",
    modifiedTime: "2025-08-06T09:13:57.793Z",
  },
  {
    id: 48,
    name: "apa-label-color",
    alias: [],
    componentName: "IconApaLabelColor",
    componentAlias: [],
    title: "",
    category: "KAPA",
    categoryCN: "KAPA",
    author: "KSW",
    tag: [],
    projectName: "KAPA",
    modifiedTime: "2025-08-28T02:48:40.933Z",
  },
  {
    id: 49,
    name: "apa-left",
    alias: [],
    componentName: "IconApaLeft",
    componentAlias: [],
    title: "",
    category: "KAPA",
    categoryCN: "KAPA",
    author: "KSW",
    tag: [],
    projectName: "KAPA",
    modifiedTime: "2025-11-13T06:15:00.918Z",
  },
  {
    id: 50,
    name: "apa-like-fill",
    alias: [],
    componentName: "IconApaLikeFill",
    componentAlias: [],
    title: "",
    category: "KAPA",
    categoryCN: "KAPA",
    author: "KSW",
    tag: [],
    projectName: "KAPA",
    modifiedTime: "2025-08-28T02:48:19.117Z",
  },
  {
    id: 51,
    name: "apa-like",
    alias: [],
    componentName: "IconApaLike",
    componentAlias: [],
    title: "",
    category: "KAPA",
    categoryCN: "KAPA",
    author: "KSW",
    tag: [],
    projectName: "KAPA",
    modifiedTime: "2025-08-28T02:48:19.125Z",
  },
  {
    id: 52,
    name: "apa-logo-color",
    alias: [],
    componentName: "IconApaLogoColor",
    componentAlias: [],
    title: "",
    category: "KAPA",
    categoryCN: "KAPA",
    author: "KSW",
    tag: [],
    projectName: "KAPA",
    modifiedTime: "2025-10-13T03:25:37.963Z",
  },
  {
    id: 53,
    name: "apa-manage-fill",
    alias: [],
    componentName: "IconApaManageFill",
    componentAlias: [],
    title: "",
    category: "KAPA",
    categoryCN: "KAPA",
    author: "KSW",
    tag: [],
    projectName: "KAPA",
    modifiedTime: "2025-09-09T09:41:03.074Z",
  },
  {
    id: 54,
    name: "apa-manage",
    alias: [],
    componentName: "IconApaManage",
    componentAlias: [],
    title: "",
    category: "KAPA",
    categoryCN: "KAPA",
    author: "KSW",
    tag: [],
    projectName: "KAPA",
    modifiedTime: "2025-09-09T09:41:03.075Z",
  },
  {
    id: 55,
    name: "apa-menu-expand",
    alias: [],
    componentName: "IconApaMenuExpand",
    componentAlias: [],
    title: "",
    category: "KAPA",
    categoryCN: "KAPA",
    author: "KSW",
    tag: [],
    projectName: "KAPA",
    modifiedTime: "2025-08-28T02:48:40.933Z",
  },
  {
    id: 56,
    name: "apa-menu-fold",
    alias: [],
    componentName: "IconApaMenuFold",
    componentAlias: [],
    title: "",
    category: "KAPA",
    categoryCN: "KAPA",
    author: "KSW",
    tag: [],
    projectName: "KAPA",
    modifiedTime: "2025-08-28T02:48:40.933Z",
  },
  {
    id: 57,
    name: "apa-model-set",
    alias: [],
    componentName: "IconApaModelSet",
    componentAlias: [],
    title: "",
    category: "KAPA",
    categoryCN: "KAPA",
    author: "KSW",
    tag: [],
    projectName: "KAPA",
    modifiedTime: "2025-10-13T03:25:37.963Z",
  },
  {
    id: 58,
    name: "apa-model",
    alias: [],
    componentName: "IconApaModel",
    componentAlias: [],
    title: "",
    category: "KAPA",
    categoryCN: "KAPA",
    author: "KSW",
    tag: [],
    projectName: "KAPA",
    modifiedTime: "2025-08-15T02:26:32.716Z",
  },
  {
    id: 59,
    name: "apa-more",
    alias: [],
    componentName: "IconApaMore",
    componentAlias: [],
    title: "",
    category: "KAPA",
    categoryCN: "KAPA",
    author: "KSW",
    tag: [],
    projectName: "KAPA",
    modifiedTime: "2025-11-13T06:15:00.918Z",
  },
  {
    id: 60,
    name: "apa-node",
    alias: [],
    componentName: "IconApaNode",
    componentAlias: [],
    title: "",
    category: "KAPA",
    categoryCN: "KAPA",
    author: "KSW",
    tag: [],
    projectName: "KAPA",
    modifiedTime: "2025-08-15T02:26:32.716Z",
  },
  {
    id: 61,
    name: "apa-normal-win",
    alias: [],
    componentName: "IconApaNormalWin",
    componentAlias: [],
    title: "",
    category: "KAPA",
    categoryCN: "KAPA",
    author: "KSW",
    tag: [],
    projectName: "KAPA",
    modifiedTime: "2025-10-13T03:25:37.963Z",
  },
  {
    id: 62,
    name: "apa-otz-prompt-w-color",
    alias: [],
    componentName: "IconApaOtzPromptWColor",
    componentAlias: [],
    title: "",
    category: "KAPA",
    categoryCN: "KAPA",
    author: "KSW",
    tag: [],
    projectName: "KAPA",
    modifiedTime: "2025-11-13T06:15:00.919Z",
  },
  {
    id: 63,
    name: "apa-pdf-color",
    alias: [],
    componentName: "IconApaPdfColor",
    componentAlias: [],
    title: "",
    category: "KAPA",
    categoryCN: "KAPA",
    author: "KSW",
    tag: [],
    projectName: "KAPA",
    modifiedTime: "2025-10-13T03:25:37.963Z",
  },
  {
    id: 64,
    name: "apa-personal",
    alias: [],
    componentName: "IconApaPersonal",
    componentAlias: [],
    title: "",
    category: "KAPA",
    categoryCN: "KAPA",
    author: "KSW",
    tag: [],
    projectName: "KAPA",
    modifiedTime: "2025-09-12T11:02:29.096Z",
  },
  {
    id: 65,
    name: "apa-plan",
    alias: [],
    componentName: "IconApaPlan",
    componentAlias: [],
    title: "",
    category: "KAPA",
    categoryCN: "KAPA",
    author: "KSW",
    tag: [],
    projectName: "KAPA",
    modifiedTime: "2025-08-06T09:13:57.793Z",
  },
  {
    id: 66,
    name: "apa-port",
    alias: [],
    componentName: "IconApaPort",
    componentAlias: [],
    title: "",
    category: "KAPA",
    categoryCN: "KAPA",
    author: "KSW",
    tag: [],
    projectName: "KAPA",
    modifiedTime: "2025-08-28T02:48:40.934Z",
  },
  {
    id: 67,
    name: "apa-ppt-color",
    alias: [],
    componentName: "IconApaPptColor",
    componentAlias: [],
    title: "",
    category: "KAPA",
    categoryCN: "KAPA",
    author: "KSW",
    tag: [],
    projectName: "KAPA",
    modifiedTime: "2025-10-13T03:25:37.963Z",
  },
  {
    id: 68,
    name: "apa-prepare",
    alias: [],
    componentName: "IconApaPrepare",
    componentAlias: [],
    title: "",
    category: "KAPA",
    categoryCN: "KAPA",
    author: "KSW",
    tag: [],
    projectName: "KAPA",
    modifiedTime: "2025-10-13T03:25:37.963Z",
  },
  {
    id: 69,
    name: "apa-process",
    alias: [],
    componentName: "IconApaProcess",
    componentAlias: [],
    title: "",
    category: "KAPA",
    categoryCN: "KAPA",
    author: "KSW",
    tag: [],
    projectName: "KAPA",
    modifiedTime: "2025-07-30T02:08:30.010Z",
  },
  {
    id: 70,
    name: "apa-process2",
    alias: [],
    componentName: "IconApaProcess2",
    componentAlias: [],
    title: "",
    category: "KAPA",
    categoryCN: "KAPA",
    author: "KSW",
    tag: [],
    projectName: "KAPA",
    modifiedTime: "2025-08-06T09:13:57.793Z",
  },
  {
    id: 71,
    name: "apa-prompt-w",
    alias: [],
    componentName: "IconApaPromptW",
    componentAlias: [],
    title: "",
    category: "KAPA",
    categoryCN: "KAPA",
    author: "KSW",
    tag: [],
    projectName: "KAPA",
    modifiedTime: "2025-08-15T02:26:32.717Z",
  },
  {
    id: 72,
    name: "apa-prompt",
    alias: [],
    componentName: "IconApaPrompt",
    componentAlias: [],
    title: "",
    category: "KAPA",
    categoryCN: "KAPA",
    author: "KSW",
    tag: [],
    projectName: "KAPA",
    modifiedTime: "2025-08-15T02:26:32.721Z",
  },
  {
    id: 73,
    name: "apa-reduce",
    alias: [],
    componentName: "IconApaReduce",
    componentAlias: [],
    title: "",
    category: "KAPA",
    categoryCN: "KAPA",
    author: "KSW",
    tag: [],
    projectName: "KAPA",
    modifiedTime: "2025-08-15T02:26:32.722Z",
  },
  {
    id: 74,
    name: "apa-refresh",
    alias: [],
    componentName: "IconApaRefresh",
    componentAlias: [],
    title: "",
    category: "KAPA",
    categoryCN: "KAPA",
    author: "KSW",
    tag: [],
    projectName: "KAPA",
    modifiedTime: "2025-10-13T03:25:37.964Z",
  },
  {
    id: 75,
    name: "apa-regen",
    alias: [],
    componentName: "IconApaRegen",
    componentAlias: [],
    title: "",
    category: "KAPA",
    categoryCN: "KAPA",
    author: "KSW",
    tag: [],
    projectName: "KAPA",
    modifiedTime: "2025-08-28T02:48:19.133Z",
  },
  {
    id: 76,
    name: "apa-remote-desk",
    alias: [],
    componentName: "IconApaRemoteDesk",
    componentAlias: [],
    title: "",
    category: "KAPA",
    categoryCN: "KAPA",
    author: "KSW",
    tag: [],
    projectName: "KAPA",
    modifiedTime: "2025-11-13T06:15:00.919Z",
  },
  {
    id: 77,
    name: "apa-remote-desk2",
    alias: [],
    componentName: "IconApaRemoteDesk2",
    componentAlias: [],
    title: "",
    category: "KAPA",
    categoryCN: "KAPA",
    author: "KSW",
    tag: [],
    projectName: "KAPA",
    modifiedTime: "2025-11-13T06:15:00.919Z",
  },
  {
    id: 78,
    name: "apa-retract-operation",
    alias: [],
    componentName: "IconApaRetractOperation",
    componentAlias: [],
    title: "",
    category: "KAPA",
    categoryCN: "KAPA",
    author: "KSW",
    tag: [],
    projectName: "KAPA",
    modifiedTime: "2025-11-13T06:15:00.920Z",
  },
  {
    id: 79,
    name: "apa-return",
    alias: [],
    componentName: "IconApaReturn",
    componentAlias: [],
    title: "",
    category: "KAPA",
    categoryCN: "KAPA",
    author: "KSW",
    tag: [],
    projectName: "KAPA",
    modifiedTime: "2025-08-06T09:13:57.793Z",
  },
  {
    id: 80,
    name: "apa-right",
    alias: [],
    componentName: "IconApaRight",
    componentAlias: [],
    title: "",
    category: "KAPA",
    categoryCN: "KAPA",
    author: "KSW",
    tag: [],
    projectName: "KAPA",
    modifiedTime: "2025-11-13T06:15:00.920Z",
  },
  {
    id: 81,
    name: "apa-robot",
    alias: [],
    componentName: "IconApaRobot",
    componentAlias: [],
    title: "",
    category: "KAPA",
    categoryCN: "KAPA",
    author: "KSW",
    tag: [],
    projectName: "KAPA",
    modifiedTime: "2025-09-09T09:41:03.075Z",
  },
  {
    id: 82,
    name: "apa-role",
    alias: [],
    componentName: "IconApaRole",
    componentAlias: [],
    title: "",
    category: "KAPA",
    categoryCN: "KAPA",
    author: "KSW",
    tag: [],
    projectName: "KAPA",
    modifiedTime: "2025-09-09T09:41:03.075Z",
  },
  {
    id: 83,
    name: "apa-running",
    alias: [],
    componentName: "IconApaRunning",
    componentAlias: [],
    title: "",
    category: "KAPA",
    categoryCN: "KAPA",
    author: "KSW",
    tag: [],
    projectName: "KAPA",
    modifiedTime: "2025-09-12T11:02:29.097Z",
  },
  {
    id: 84,
    name: "apa-scan",
    alias: [],
    componentName: "IconApaScan",
    componentAlias: [],
    title: "",
    category: "KAPA",
    categoryCN: "KAPA",
    author: "KSW",
    tag: [],
    projectName: "KAPA",
    modifiedTime: "2025-08-28T02:48:40.934Z",
  },
  {
    id: 85,
    name: "apa-scene-fill",
    alias: [],
    componentName: "IconApaSceneFill",
    componentAlias: [],
    title: "",
    category: "KAPA",
    categoryCN: "KAPA",
    author: "KSW",
    tag: [],
    projectName: "KAPA",
    modifiedTime: "2025-10-13T03:25:37.964Z",
  },
  {
    id: 86,
    name: "apa-scene",
    alias: [],
    componentName: "IconApaScene",
    componentAlias: [],
    title: "",
    category: "KAPA",
    categoryCN: "KAPA",
    author: "KSW",
    tag: [],
    projectName: "KAPA",
    modifiedTime: "2025-10-13T03:25:37.964Z",
  },
  {
    id: 87,
    name: "apa-scene2",
    alias: [],
    componentName: "IconApaScene2",
    componentAlias: [],
    title: "",
    category: "KAPA",
    categoryCN: "KAPA",
    author: "KSW",
    tag: [],
    projectName: "KAPA",
    modifiedTime: "2025-10-13T03:25:37.964Z",
  },
  {
    id: 88,
    name: "apa-search",
    alias: [],
    componentName: "IconApaSearch",
    componentAlias: [],
    title: "",
    category: "KAPA",
    categoryCN: "KAPA",
    author: "KSW",
    tag: [],
    projectName: "KAPA",
    modifiedTime: "2025-08-28T02:48:40.934Z",
  },
  {
    id: 89,
    name: "apa-share",
    alias: [],
    componentName: "IconApaShare",
    componentAlias: [],
    title: "",
    category: "KAPA",
    categoryCN: "KAPA",
    author: "KSW",
    tag: [],
    projectName: "KAPA",
    modifiedTime: "2025-11-13T06:15:00.920Z",
  },
  {
    id: 90,
    name: "apa-small-win",
    alias: [],
    componentName: "IconApaSmallWin",
    componentAlias: [],
    title: "",
    category: "KAPA",
    categoryCN: "KAPA",
    author: "KSW",
    tag: [],
    projectName: "KAPA",
    modifiedTime: "2025-10-13T03:25:37.964Z",
  },
  {
    id: 91,
    name: "apa-spanner",
    alias: [],
    componentName: "IconApaSpanner",
    componentAlias: [],
    title: "",
    category: "KAPA",
    categoryCN: "KAPA",
    author: "KSW",
    tag: [],
    projectName: "KAPA",
    modifiedTime: "2025-09-09T09:41:03.075Z",
  },
  {
    id: 92,
    name: "apa-SSE",
    alias: [],
    componentName: "IconApaSSE",
    componentAlias: [],
    title: "",
    category: "KAPA",
    categoryCN: "KAPA",
    author: "KSW",
    tag: [],
    projectName: "KAPA",
    modifiedTime: "2025-08-28T02:48:40.931Z",
  },
  {
    id: 93,
    name: "apa-STDIO",
    alias: [],
    componentName: "IconApaSTDIO",
    componentAlias: [],
    title: "",
    category: "KAPA",
    categoryCN: "KAPA",
    author: "KSW",
    tag: [],
    projectName: "KAPA",
    modifiedTime: "2025-08-28T02:48:40.931Z",
  },
  {
    id: 94,
    name: "apa-struct-form",
    alias: [],
    componentName: "IconApaStructForm",
    componentAlias: [],
    title: "",
    category: "KAPA",
    categoryCN: "KAPA",
    author: "KSW",
    tag: [],
    projectName: "KAPA",
    modifiedTime: "2025-08-15T02:26:32.722Z",
  },
  {
    id: 95,
    name: "apa-success",
    alias: [],
    componentName: "IconApaSuccess",
    componentAlias: [],
    title: "",
    category: "KAPA",
    categoryCN: "KAPA",
    author: "KSW",
    tag: [],
    projectName: "KAPA",
    modifiedTime: "2025-11-13T06:15:00.921Z",
  },
  {
    id: 96,
    name: "apa-success1",
    alias: [],
    componentName: "IconApaSuccess1",
    componentAlias: [],
    title: "",
    category: "KAPA",
    categoryCN: "KAPA",
    author: "KSW",
    tag: [],
    projectName: "KAPA",
    modifiedTime: "2025-11-13T06:15:00.921Z",
  },
  {
    id: 97,
    name: "apa-sum-prompt-w",
    alias: [],
    componentName: "IconApaSumPromptW",
    componentAlias: [],
    title: "",
    category: "KAPA",
    categoryCN: "KAPA",
    author: "KSW",
    tag: [],
    projectName: "KAPA",
    modifiedTime: "2025-08-15T02:26:32.722Z",
  },
  {
    id: 98,
    name: "apa-task",
    alias: [],
    componentName: "IconApaTask",
    componentAlias: [],
    title: "",
    category: "KAPA",
    categoryCN: "KAPA",
    author: "KSW",
    tag: [],
    projectName: "KAPA",
    modifiedTime: "2025-11-13T06:15:00.921Z",
  },
  {
    id: 99,
    name: "apa-task2",
    alias: [],
    componentName: "IconApaTask2",
    componentAlias: [],
    title: "",
    category: "KAPA",
    categoryCN: "KAPA",
    author: "KSW",
    tag: [],
    projectName: "KAPA",
    modifiedTime: "2025-11-13T06:15:00.921Z",
  },
  {
    id: 100,
    name: "apa-test",
    alias: [],
    componentName: "IconApaTest",
    componentAlias: [],
    title: "",
    category: "KAPA",
    categoryCN: "KAPA",
    author: "KSW",
    tag: [],
    projectName: "KAPA",
    modifiedTime: "2025-08-28T02:48:40.935Z",
  },
  {
    id: 101,
    name: "apa-text",
    alias: [],
    componentName: "IconApaText",
    componentAlias: [],
    title: "",
    category: "KAPA",
    categoryCN: "KAPA",
    author: "KSW",
    tag: [],
    projectName: "KAPA",
    modifiedTime: "2025-08-15T02:26:32.722Z",
  },
  {
    id: 102,
    name: "apa-thinking-color",
    alias: [],
    componentName: "IconApaThinkingColor",
    componentAlias: [],
    title: "",
    category: "KAPA",
    categoryCN: "KAPA",
    author: "KSW",
    tag: [],
    projectName: "KAPA",
    modifiedTime: "2025-11-13T06:15:00.921Z",
  },
  {
    id: 103,
    name: "apa-time",
    alias: [],
    componentName: "IconApaTime",
    componentAlias: [],
    title: "",
    category: "KAPA",
    categoryCN: "KAPA",
    author: "KSW",
    tag: [],
    projectName: "KAPA",
    modifiedTime: "2025-09-09T09:41:03.076Z",
  },
  {
    id: 104,
    name: "apa-tool-2-color",
    alias: [],
    componentName: "IconApaTool2Color",
    componentAlias: [],
    title: "",
    category: "KAPA",
    categoryCN: "KAPA",
    author: "KSW",
    tag: [],
    projectName: "KAPA",
    modifiedTime: "2025-11-13T06:15:00.922Z",
  },
  {
    id: 105,
    name: "apa-tool-color",
    alias: [],
    componentName: "IconApaToolColor",
    componentAlias: [],
    title: "",
    category: "KAPA",
    categoryCN: "KAPA",
    author: "KSW",
    tag: [],
    projectName: "KAPA",
    modifiedTime: "2025-11-13T06:15:00.922Z",
  },
  {
    id: 106,
    name: "apa-tool",
    alias: [],
    componentName: "IconApaTool",
    componentAlias: [],
    title: "",
    category: "KAPA",
    categoryCN: "KAPA",
    author: "KSW",
    tag: [],
    projectName: "KAPA",
    modifiedTime: "2025-07-30T02:08:30.010Z",
  },
  {
    id: 107,
    name: "apa-txt-color",
    alias: [],
    componentName: "IconApaTxtColor",
    componentAlias: [],
    title: "",
    category: "KAPA",
    categoryCN: "KAPA",
    author: "KSW",
    tag: [],
    projectName: "KAPA",
    modifiedTime: "2025-10-13T03:25:37.964Z",
  },
  {
    id: 108,
    name: "apa-unk-file-color",
    alias: [],
    componentName: "IconApaUnkFileColor",
    componentAlias: [],
    title: "",
    category: "KAPA",
    categoryCN: "KAPA",
    author: "KSW",
    tag: [],
    projectName: "KAPA",
    modifiedTime: "2025-11-13T06:15:00.922Z",
  },
  {
    id: 109,
    name: "apa-video-color",
    alias: [],
    componentName: "IconApaVideoColor",
    componentAlias: [],
    title: "",
    category: "KAPA",
    categoryCN: "KAPA",
    author: "KSW",
    tag: [],
    projectName: "KAPA",
    modifiedTime: "2025-10-13T03:25:37.964Z",
  },
  {
    id: 110,
    name: "apa-voice-play",
    alias: [],
    componentName: "IconApaVoicePlay",
    componentAlias: [],
    title: "",
    category: "KAPA",
    categoryCN: "KAPA",
    author: "KSW",
    tag: [],
    projectName: "KAPA",
    modifiedTime: "2025-08-15T02:26:32.722Z",
  },
  {
    id: 111,
    name: "apa-voice-to-text",
    alias: [],
    componentName: "IconApaVoiceToText",
    componentAlias: [],
    title: "",
    category: "KAPA",
    categoryCN: "KAPA",
    author: "KSW",
    tag: [],
    projectName: "KAPA",
    modifiedTime: "2025-08-15T02:26:32.723Z",
  },
  {
    id: 112,
    name: "apa-word-color",
    alias: [],
    componentName: "IconApaWordColor",
    componentAlias: [],
    title: "",
    category: "KAPA",
    categoryCN: "KAPA",
    author: "KSW",
    tag: [],
    projectName: "KAPA",
    modifiedTime: "2025-10-13T03:25:37.964Z",
  },
  {
    id: 113,
    name: "apa-workflow",
    alias: [],
    componentName: "IconApaWorkflow",
    componentAlias: [],
    title: "",
    category: "KAPA",
    categoryCN: "KAPA",
    author: "KSW",
    tag: [],
    projectName: "KAPA",
    modifiedTime: "2025-09-09T09:41:03.076Z",
  },
  {
    id: 114,
    name: "apa-workflow2",
    alias: [],
    componentName: "IconApaWorkflow2",
    componentAlias: [],
    title: "",
    category: "KAPA",
    categoryCN: "KAPA",
    author: "KSW",
    tag: [],
    projectName: "KAPA",
    modifiedTime: "2025-11-13T06:15:00.922Z",
  },
  {
    id: 115,
    name: "apa-zoom",
    alias: [],
    componentName: "IconApaZoom",
    componentAlias: [],
    title: "",
    category: "KAPA",
    categoryCN: "KAPA",
    author: "KSW",
    tag: [],
    projectName: "KAPA",
    modifiedTime: "2025-10-13T03:25:37.964Z",
  },
];
