export const iconsDataBase = [
  {
    id: 0,
    name: "add",
    alias: [],
    componentName: "IconAdd",
    componentAlias: [],
    title: "添加",
    category: "Character",
    categoryCN: "符号标识",
    author: "KSW",
    tag: ["新建", "增加", "创建"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.933Z",
  },
  {
    id: 1,
    name: "alarm-clock-color",
    alias: [],
    componentName: "IconAlarmClockColor",
    componentAlias: [],
    title: "闹钟-颜色",
    category: "Other",
    categoryCN: "其他",
    author: "KSW",
    tag: [],
    projectName: "base",
    modifiedTime: "2025-02-10T09:37:50.000Z",
  },
  {
    id: 2,
    name: "alarm-clock",
    alias: [],
    componentName: "IconAlarmClock",
    componentAlias: [],
    title: "闹钟",
    category: "Other",
    categoryCN: "其他",
    author: "KSW",
    tag: [],
    projectName: "base",
    modifiedTime: "2025-02-10T09:37:50.000Z",
  },
  {
    id: 3,
    name: "aom-menu-AOMRZ-color",
    alias: [],
    componentName: "IconAomMenuAOMRZColor",
    componentAlias: [],
    title: "AOM日志",
    category: "AOM Menu",
    categoryCN: "AOM 菜单",
    author: "KSW",
    tag: ["AOM", "日志"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.934Z",
  },
  {
    id: 4,
    name: "aom-menu-BBCX-color",
    alias: [],
    componentName: "IconAomMenuBBCXColor",
    componentAlias: [],
    title: "报表查询",
    category: "AOM Menu",
    categoryCN: "AOM 菜单",
    author: "KSW",
    tag: ["AOM", "报表"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.934Z",
  },
  {
    id: 5,
    name: "aom-menu-BBSH-color",
    alias: [],
    componentName: "IconAomMenuBBSHColor",
    componentAlias: [],
    title: "菜单按钮颜色",
    category: "UI",
    categoryCN: "用户界面元素",
    author: "KSW",
    tag: ["菜单", "按钮", "颜色", "用户界面"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.934Z",
  },
  {
    id: 6,
    name: "aom-menu-BBSJ-color",
    alias: [],
    componentName: "IconAomMenuBBSJColor",
    componentAlias: [],
    title: "菜单",
    category: "Menu",
    categoryCN: "菜单",
    author: "KSW",
    tag: ["菜单", "论坛", "颜色"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.934Z",
  },
  {
    id: 7,
    name: "aom-menu-BBYL-color",
    alias: [],
    componentName: "IconAomMenuBBYLColor",
    componentAlias: [],
    title: "",
    category: "Other",
    categoryCN: "其他",
    author: "KSW",
    tag: [],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.935Z",
  },
  {
    id: 8,
    name: "aom-menu-BCLLPZ-color",
    alias: [],
    componentName: "IconAomMenuBCLLPZColor",
    componentAlias: [],
    title: "菜单图标",
    category: "UI",
    categoryCN: "用户界面元素",
    author: "KSW",
    tag: ["菜单", "导航", "图标"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.935Z",
  },
  {
    id: 9,
    name: "aom-menu-BCZXKanban-color",
    alias: [],
    componentName: "IconAomMenuBCZXKanbanColor",
    componentAlias: [],
    title: "",
    category: "Other",
    categoryCN: "其他",
    author: "KSW",
    tag: [],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.935Z",
  },
  {
    id: 10,
    name: "aom-menu-BDCK-color",
    alias: [],
    componentName: "IconAomMenuBDCKColor",
    componentAlias: [],
    title: "菜单工具颜色",
    category: "Tools",
    categoryCN: "工具",
    author: "KSW",
    tag: ["菜单", "工具", "颜色"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.935Z",
  },
  {
    id: 11,
    name: "aom-menu-BDGL-color",
    alias: [],
    componentName: "IconAomMenuBDGLColor",
    componentAlias: [],
    title: "菜单选项颜色",
    category: "UI",
    categoryCN: "用户界面元素",
    author: "KSW",
    tag: ["菜单", "选项", "颜色", "用户界面"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.935Z",
  },
  {
    id: 12,
    name: "aom-menu-BDKanban-color",
    alias: [],
    componentName: "IconAomMenuBDKanbanColor",
    componentAlias: [],
    title: "自动化菜单",
    category: "Automation",
    categoryCN: "自动化工具",
    author: "KSW",
    tag: ["自动化", "菜单", "看板", "颜色"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.935Z",
  },
  {
    id: 13,
    name: "aom-menu-CJCL-color",
    alias: [],
    componentName: "IconAomMenuCJCLColor",
    componentAlias: [],
    title: "菜单颜色选择器",
    category: "UI",
    categoryCN: "用户界面元素",
    author: "KSW",
    tag: ["菜单", "颜色", "选择器"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.936Z",
  },
  {
    id: 14,
    name: "aom-menu-CKGL-color",
    alias: [],
    componentName: "IconAomMenuCKGLColor",
    componentAlias: [],
    title: "代码菜单",
    category: "Development",
    categoryCN: "开发工具",
    author: "KSW",
    tag: ["代码", "菜单", "颜色", "开发", "工具"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.936Z",
  },
  {
    id: 15,
    name: "aom-menu-CLJL-color",
    alias: [],
    componentName: "IconAomMenuCLJLColor",
    componentAlias: [],
    title: "菜单列表颜色",
    category: "UI",
    categoryCN: "用户界面元素",
    author: "KSW",
    tag: ["菜单", "列表", "颜色", "图标"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.936Z",
  },
  {
    id: 16,
    name: "aom-menu-CZRZ-color",
    alias: [],
    componentName: "IconAomMenuCZRZColor",
    componentAlias: [],
    title: "菜单颜色设置",
    category: "User",
    categoryCN: "用户界面",
    author: "KSW",
    tag: ["菜单", "颜色", "设置", "用户界面"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.936Z",
  },
  {
    id: 17,
    name: "aom-menu-default-color",
    alias: [],
    componentName: "IconAomMenuDefaultColor",
    componentAlias: [],
    title: "",
    category: "Other",
    categoryCN: "其他",
    author: "KSW",
    tag: [],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.951Z",
  },
  {
    id: 18,
    name: "aom-menu-DLDGL-color",
    alias: [],
    componentName: "IconAomMenuDLDGLColor",
    componentAlias: [],
    title: "菜单选项颜色",
    category: "UI",
    categoryCN: "用户界面元素",
    author: "KSW",
    tag: ["菜单", "颜色", "用户界面"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.936Z",
  },
  {
    id: 19,
    name: "aom-menu-DLDSJ-color",
    alias: [],
    componentName: "IconAomMenuDLDSJColor",
    componentAlias: [],
    title: "自动化菜单",
    category: "Automation",
    categoryCN: "自动化工具",
    author: "KSW",
    tag: ["自动化", "菜单", "动态数据监控", "彩色"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.937Z",
  },
  {
    id: 20,
    name: "aom-menu-DLDXC-color",
    alias: [],
    componentName: "IconAomMenuDLDXCColor",
    componentAlias: [],
    title: "菜单选项颜色",
    category: "User",
    categoryCN: "用户界面",
    author: "KSW",
    tag: ["菜单", "选项", "颜色", "界面"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.937Z",
  },
  {
    id: 21,
    name: "aom-menu-DLDXX-color",
    alias: [],
    componentName: "IconAomMenuDLDXXColor",
    componentAlias: [],
    title: "奥姆菜单",
    category: "Menu",
    categoryCN: "菜单图标",
    author: "KSW",
    tag: ["菜单", "颜色", "图标"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.937Z",
  },
  {
    id: 22,
    name: "aom-menu-DLDXZ-color",
    alias: [],
    componentName: "IconAomMenuDLDXZColor",
    componentAlias: [],
    title: "",
    category: "Other",
    categoryCN: "其他",
    author: "KSW",
    tag: [],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.937Z",
  },
  {
    id: 23,
    name: "aom-menu-DPGL-color",
    alias: [],
    componentName: "IconAomMenuDPGLColor",
    componentAlias: [],
    title: "大屏管理",
    category: "AOM Menu",
    categoryCN: "AOM 菜单",
    author: "KSW",
    tag: ["AOM", "大屏", "管理"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.938Z",
  },
  {
    id: 24,
    name: "aom-menu-DPYL-color",
    alias: [],
    componentName: "IconAomMenuDPYLColor",
    componentAlias: [],
    title: "大屏预览",
    category: "AOM Menu",
    categoryCN: "AOM 菜单",
    author: "KSW",
    tag: ["AOM", "大屏", "预览", "演示"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.938Z",
  },
  {
    id: 25,
    name: "aom-menu-DXSZ-color",
    alias: [],
    componentName: "IconAomMenuDXSZColor",
    componentAlias: [],
    title: "菜单设置颜色",
    category: "Menu",
    categoryCN: "菜单配置",
    author: "KSW",
    tag: ["菜单", "设置", "颜色"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.938Z",
  },
  {
    id: 26,
    name: "aom-menu-DYGX-color",
    alias: [],
    componentName: "IconAomMenuDYGXColor",
    componentAlias: [],
    title: "菜单选项",
    category: "Navigation",
    categoryCN: "导航",
    author: "KSW",
    tag: ["菜单", "选项", "导航", "界面"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.938Z",
  },
  {
    id: 27,
    name: "aom-menu-FFQDJ-color",
    alias: [],
    componentName: "IconAomMenuFFQDJColor",
    componentAlias: [],
    title: "奥姆菜单",
    category: "Menu",
    categoryCN: "菜单图标",
    author: "KSW",
    tag: ["菜单", "颜色", "图标"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.938Z",
  },
  {
    id: 28,
    name: "aom-menu-FFQSL-color",
    alias: [],
    componentName: "IconAomMenuFFQSLColor",
    componentAlias: [],
    title: "",
    category: "Other",
    categoryCN: "其他",
    author: "KSW",
    tag: [],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.939Z",
  },
  {
    id: 29,
    name: "aom-menu-FPGL-color",
    alias: [],
    componentName: "IconAomMenuFPGLColor",
    componentAlias: [],
    title: "分屏管理",
    category: "AOM Menu",
    categoryCN: "AOM 菜单",
    author: "KSW",
    tag: ["AOM", "大屏", "分屏", "管理"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.939Z",
  },
  {
    id: 30,
    name: "aom-menu-FWQPZ-color",
    alias: [],
    componentName: "IconAomMenuFWQPZColor",
    componentAlias: [],
    title: "自动化菜单配置",
    category: "Automation",
    categoryCN: "自动化工具",
    author: "KSW",
    tag: ["自动化", "菜单", "配置", "工具"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.939Z",
  },
  {
    id: 31,
    name: "aom-menu-FWQXX-color",
    alias: [],
    componentName: "IconAomMenuFWQXXColor",
    componentAlias: [],
    title: "服务器菜单",
    category: "Server",
    categoryCN: "服务器管理",
    author: "KSW",
    tag: ["服务器", "菜单", "管理", "颜色"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.939Z",
  },
  {
    id: 32,
    name: "aom-menu-GLST-color",
    alias: [],
    componentName: "IconAomMenuGLSTColor",
    componentAlias: [],
    title: "",
    category: "Other",
    categoryCN: "其他",
    author: "KSW",
    tag: [],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.939Z",
  },
  {
    id: 33,
    name: "aom-menu-GNHS-color",
    alias: [],
    componentName: "IconAomMenuGNHSColor",
    componentAlias: [],
    title: "奥姆菜单",
    category: "Menu",
    categoryCN: "菜单图标",
    author: "KSW",
    tag: ["菜单", "图标", "绿色", "圆形"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.940Z",
  },
  {
    id: 34,
    name: "aom-menu-GRBL-color",
    alias: [],
    componentName: "IconAomMenuGRBLColor",
    componentAlias: [],
    title: "奥姆菜单GRBL颜色",
    category: "Software",
    categoryCN: "软件工具",
    author: "KSW",
    tag: ["奥姆", "菜单", "GRBL", "颜色"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.940Z",
  },
  {
    id: 35,
    name: "aom-menu-HSZ-color",
    alias: [],
    componentName: "IconAomMenuHSZColor",
    componentAlias: [],
    title: "菜单选项",
    category: "Menu",
    categoryCN: "菜单选项",
    author: "KSW",
    tag: ["菜单", "选项", "HSZ颜色"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.940Z",
  },
  {
    id: 36,
    name: "aom-menu-JBGL-color",
    alias: [],
    componentName: "IconAomMenuJBGLColor",
    componentAlias: [],
    title: "菜单管理",
    category: "Menu",
    categoryCN: "菜单管理",
    author: "KSW",
    tag: ["菜单", "管理", "彩色"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.940Z",
  },
  {
    id: 37,
    name: "aom-menu-JBKanban-color",
    alias: [],
    componentName: "IconAomMenuJBKanbanColor",
    componentAlias: [],
    title: "AOM菜单",
    category: "UI",
    categoryCN: "用户界面元素",
    author: "KSW",
    tag: ["菜单", "看板", "颜色"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.940Z",
  },
  {
    id: 38,
    name: "aom-menu-JBRZ-color",
    alias: [],
    componentName: "IconAomMenuJBRZColor",
    componentAlias: [],
    title: "菜单选项",
    category: "User",
    categoryCN: "用户界面",
    author: "KSW",
    tag: ["菜单", "选项", "用户界面"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.941Z",
  },
  {
    id: 39,
    name: "aom-menu-JBSM-color",
    alias: [],
    componentName: "IconAomMenuJBSMColor",
    componentAlias: [],
    title: "菜单栏颜色",
    category: "UI",
    categoryCN: "用户界面元素",
    author: "KSW",
    tag: ["菜单", "颜色", "界面"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.941Z",
  },
  {
    id: 40,
    name: "aom-menu-JCYWPTKanban-color",
    alias: [],
    componentName: "IconAomMenuJCYWPTKanbanColor",
    componentAlias: [],
    title: "菜单",
    category: "UI",
    categoryCN: "用户界面元素",
    author: "KSW",
    tag: ["菜单", "看板", "颜色"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.941Z",
  },
  {
    id: 41,
    name: "aom-menu-JGCL-color",
    alias: [],
    componentName: "IconAomMenuJGCLColor",
    componentAlias: [],
    title: "菜单颜色选择器",
    category: "UI",
    categoryCN: "用户界面元素",
    author: "KSW",
    tag: ["菜单", "颜色", "选择器"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.941Z",
  },
  {
    id: 42,
    name: "aom-menu-JQFA-color",
    alias: [],
    componentName: "IconAomMenuJQFAColor",
    componentAlias: [],
    title: "菜单颜色",
    category: "UI",
    categoryCN: "用户界面元素",
    author: "KSW",
    tag: ["菜单", "颜色", "界面"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.941Z",
  },
  {
    id: 43,
    name: "aom-menu-JRLC-color",
    alias: [],
    componentName: "IconAomMenuJRLCColor",
    componentAlias: [],
    title: "菜单选项颜色",
    category: "User",
    categoryCN: "用户界面",
    author: "KSW",
    tag: ["菜单", "颜色", "用户界面"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.942Z",
  },
  {
    id: 44,
    name: "aom-menu-JXCX-color",
    alias: [],
    componentName: "IconAomMenuJXCXColor",
    componentAlias: [],
    title: "",
    category: "Other",
    categoryCN: "其他",
    author: "KSW",
    tag: [],
    projectName: "base",
    modifiedTime: "2024-12-02T07:03:50.000Z",
  },
  {
    id: 45,
    name: "aom-menu-JXLL-color",
    alias: [],
    componentName: "IconAomMenuJXLLColor",
    componentAlias: [],
    title: "",
    category: "Other",
    categoryCN: "其他",
    author: "KSW",
    tag: [],
    projectName: "base",
    modifiedTime: "2024-12-02T07:03:50.000Z",
  },
  {
    id: 46,
    name: "aom-menu-JXPZ-color",
    alias: [],
    componentName: "IconAomMenuJXPZColor",
    componentAlias: [],
    title: "",
    category: "Other",
    categoryCN: "其他",
    author: "KSW",
    tag: [],
    projectName: "base",
    modifiedTime: "2024-12-02T07:07:36.397Z",
  },
  {
    id: 47,
    name: "aom-menu-JXSH-color",
    alias: [],
    componentName: "IconAomMenuJXSHColor",
    componentAlias: [],
    title: "",
    category: "Other",
    categoryCN: "其他",
    author: "KSW",
    tag: [],
    projectName: "base",
    modifiedTime: "2024-12-02T07:03:50.000Z",
  },
  {
    id: 48,
    name: "aom-menu-JZGL-color",
    alias: [],
    componentName: "IconAomMenuJZGLColor",
    componentAlias: [],
    title: "",
    category: "Other",
    categoryCN: "其他",
    author: "KSW",
    tag: [],
    projectName: "base",
    modifiedTime: "2025-01-10T07:39:07.636Z",
  },
  {
    id: 49,
    name: "aom-menu-JZJK-color",
    alias: [],
    componentName: "IconAomMenuJZJKColor",
    componentAlias: [],
    title: "",
    category: "Other",
    categoryCN: "其他",
    author: "KSW",
    tag: [],
    projectName: "base",
    modifiedTime: "2025-01-10T07:37:13.967Z",
  },
  {
    id: 50,
    name: "aom-menu-KZTGL-color",
    alias: [],
    componentName: "IconAomMenuKZTGLColor",
    componentAlias: [],
    title: "奥姆菜单",
    category: "Menu",
    categoryCN: "菜单工具",
    author: "KSW",
    tag: ["菜单", "管理", "工具", "彩色"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.942Z",
  },
  {
    id: 51,
    name: "aom-menu-LCCK-color",
    alias: [],
    componentName: "IconAomMenuLCCKColor",
    componentAlias: [],
    title: "菜单选项颜色",
    category: "User",
    categoryCN: "用户界面",
    author: "KSW",
    tag: ["菜单", "颜色", "用户界面"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.942Z",
  },
  {
    id: 52,
    name: "aom-menu-LCJG-color",
    alias: [],
    componentName: "IconAomMenuLCJGColor",
    componentAlias: [],
    title: "菜单图标",
    category: "UI",
    categoryCN: "用户界面元素",
    author: "KSW",
    tag: ["菜单", "导航", "图标"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.942Z",
  },
  {
    id: 53,
    name: "aom-menu-LCKanban-color",
    alias: [],
    componentName: "IconAomMenuLCKanbanColor",
    componentAlias: [],
    title: "菜单",
    category: "UI",
    categoryCN: "用户界面元素",
    author: "KSW",
    tag: ["菜单", "看板", "颜色"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.942Z",
  },
  {
    id: 54,
    name: "aom-menu-LCMB-color",
    alias: [],
    componentName: "IconAomMenuLCMBColor",
    componentAlias: [],
    title: "菜单图标",
    category: "UI",
    categoryCN: "用户界面元素",
    author: "KSW",
    tag: ["菜单", "导航", "图标"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.943Z",
  },
  {
    id: 55,
    name: "aom-menu-LCSH-color",
    alias: [],
    componentName: "IconAomMenuLCSHColor",
    componentAlias: [],
    title: "菜单选项",
    category: "Navigation",
    categoryCN: "导航",
    author: "KSW",
    tag: ["菜单", "选项", "导航"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.943Z",
  },
  {
    id: 56,
    name: "aom-menu-LCST-color",
    alias: [],
    componentName: "IconAomMenuLCSTColor",
    componentAlias: [],
    title: "菜单图标",
    category: "Menu",
    categoryCN: "菜单",
    author: "KSW",
    tag: ["菜单", "导航", "选项"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.943Z",
  },
  {
    id: 57,
    name: "aom-menu-LYCDL-color",
    alias: [],
    componentName: "IconAomMenuLYCDLColor",
    componentAlias: [],
    title: "菜单图标",
    category: "UI",
    categoryCN: "用户界面元素",
    author: "KSW",
    tag: ["菜单", "导航", "图标"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.944Z",
  },
  {
    id: 58,
    name: "aom-menu-MBCS-color",
    alias: [],
    componentName: "IconAomMenuMBCSColor",
    componentAlias: [],
    title: "",
    category: "Other",
    categoryCN: "其他",
    author: "KSW",
    tag: [],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.944Z",
  },
  {
    id: 59,
    name: "aom-menu-MBGL-color",
    alias: [],
    componentName: "IconAomMenuMBGLColor",
    componentAlias: [],
    title: "菜单MBGL颜色",
    category: "Menu",
    categoryCN: "菜单",
    author: "KSW",
    tag: ["菜单", "MBGL", "颜色"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.944Z",
  },
  {
    id: 60,
    name: "aom-menu-MJRW-color",
    alias: [],
    componentName: "IconAomMenuMJRWColor",
    componentAlias: [],
    title: "",
    category: "Other",
    categoryCN: "其他",
    author: "KSW",
    tag: [],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.945Z",
  },
  {
    id: 61,
    name: "aom-menu-QDGL-color",
    alias: [],
    componentName: "IconAomMenuQDGLColor",
    componentAlias: [],
    title: "质量管理菜单",
    category: "Quality",
    categoryCN: "质量管理",
    author: "KSW",
    tag: ["质量管理", "菜单", "图标"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.945Z",
  },
  {
    id: 62,
    name: "aom-menu-QJBL-color",
    alias: [],
    componentName: "IconAomMenuQJBLColor",
    componentAlias: [],
    title: "菜单图标",
    category: "UI",
    categoryCN: "用户界面元素",
    author: "KSW",
    tag: ["菜单", "导航", "界面", "图标"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.945Z",
  },
  {
    id: 63,
    name: "aom-menu-QXGL-color",
    alias: [],
    componentName: "IconAomMenuQXGLColor",
    componentAlias: [],
    title: "菜单",
    category: "Menu",
    categoryCN: "菜单管理",
    author: "KSW",
    tag: ["菜单", "权限管理", "颜色"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.945Z",
  },
  {
    id: 64,
    name: "aom-menu-RJBS-color",
    alias: [],
    componentName: "IconAomMenuRJBSColor",
    componentAlias: [],
    title: "",
    category: "Other",
    categoryCN: "其他",
    author: "KSW",
    tag: [],
    projectName: "base",
    modifiedTime: "2024-12-03T06:21:58.000Z",
  },
  {
    id: 65,
    name: "aom-menu-RJGL-color",
    alias: [],
    componentName: "IconAomMenuRJGLColor",
    componentAlias: [],
    title: "",
    category: "Other",
    categoryCN: "其他",
    author: "KSW",
    tag: [],
    projectName: "base",
    modifiedTime: "2024-12-03T06:21:58.000Z",
  },
  {
    id: 66,
    name: "aom-menu-RLPZ-color",
    alias: [],
    componentName: "IconAomMenuRLPZColor",
    componentAlias: [],
    title: "奥姆菜单",
    category: "Menu",
    categoryCN: "菜单图标",
    author: "KSW",
    tag: ["菜单", "颜色", "图标"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.945Z",
  },
  {
    id: 67,
    name: "aom-menu-RWCX-color",
    alias: [],
    componentName: "IconAomMenuRWCXColor",
    componentAlias: [],
    title: "菜单列表颜色",
    category: "UI",
    categoryCN: "用户界面元素",
    author: "KSW",
    tag: ["菜单", "列表", "颜色", "用户界面"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.946Z",
  },
  {
    id: 68,
    name: "aom-menu-RWGL-color",
    alias: [],
    componentName: "IconAomMenuRWGLColor",
    componentAlias: [],
    title: "菜单列表",
    category: "UI",
    categoryCN: "用户界面元素",
    author: "KSW",
    tag: ["菜单", "列表", "彩色", "图标"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.946Z",
  },
  {
    id: 69,
    name: "aom-menu-RWXQ-color",
    alias: [],
    componentName: "IconAomMenuRWXQColor",
    componentAlias: [],
    title: "菜单选项颜色",
    category: "UI",
    categoryCN: "用户界面元素",
    author: "KSW",
    tag: ["菜单", "选项", "颜色", "用户界面"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.946Z",
  },
  {
    id: 70,
    name: "aom-menu-RYFA-color",
    alias: [],
    componentName: "IconAomMenuRYFAColor",
    componentAlias: [],
    title: "菜单选项",
    category: "User",
    categoryCN: "用户界面",
    author: "KSW",
    tag: ["菜单", "选项", "用户界面"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.946Z",
  },
  {
    id: 71,
    name: "aom-menu-RZLC-color",
    alias: [],
    componentName: "IconAomMenuRZLCColor",
    componentAlias: [],
    title: "菜单选项颜色",
    category: "UI",
    categoryCN: "用户界面元素",
    author: "KSW",
    tag: ["菜单", "选项", "颜色", "界面"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.947Z",
  },
  {
    id: 72,
    name: "aom-menu-SBST-color",
    alias: [],
    componentName: "IconAomMenuSBSTColor",
    componentAlias: [],
    title: "菜单选项颜色",
    category: "User",
    categoryCN: "用户界面",
    author: "KSW",
    tag: ["菜单", "选项", "颜色", "用户界面"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.947Z",
  },
  {
    id: 73,
    name: "aom-menu-SJCX-color",
    alias: [],
    componentName: "IconAomMenuSJCXColor",
    componentAlias: [],
    title: "自动化菜单",
    category: "Automation",
    categoryCN: "自动化工具",
    author: "KSW",
    tag: ["自动化", "菜单", "系统检查", "彩色"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.947Z",
  },
  {
    id: 74,
    name: "aom-menu-SJGL-color",
    alias: [],
    componentName: "IconAomMenuSJGLColor",
    componentAlias: [],
    title: "菜单设置颜色",
    category: "Menu",
    categoryCN: "菜单设置",
    author: "KSW",
    tag: ["菜单", "设置", "颜色"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.947Z",
  },
  {
    id: 75,
    name: "aom-menu-SJHB-color",
    alias: [],
    componentName: "IconAomMenuSJHBColor",
    componentAlias: [],
    title: "奥姆菜单SJHB颜色",
    category: "Software",
    categoryCN: "软件工具",
    author: "KSW",
    tag: ["菜单", "颜色", "软件", "工具"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.947Z",
  },
  {
    id: 76,
    name: "aom-menu-SJKLJ-color",
    alias: [],
    componentName: "IconAomMenuSJKLJColor",
    componentAlias: [],
    title: "菜单选项颜色",
    category: "UI",
    categoryCN: "用户界面元素",
    author: "KSW",
    tag: ["菜单", "选项", "颜色", "用户界面"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.948Z",
  },
  {
    id: 77,
    name: "aom-menu-SSSJ-color",
    alias: [],
    componentName: "IconAomMenuSSSJColor",
    componentAlias: [],
    title: "菜单信息颜色",
    category: "UI",
    categoryCN: "用户界面元素",
    author: "KSW",
    tag: ["菜单", "信息", "颜色"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.948Z",
  },
  {
    id: 78,
    name: "aom-menu-TZJL-color",
    alias: [],
    componentName: "IconAomMenuTZJLColor",
    componentAlias: [],
    title: "菜单项颜色",
    category: "UI",
    categoryCN: "用户界面元素",
    author: "KSW",
    tag: ["菜单", "颜色", "界面", "设计"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.948Z",
  },
  {
    id: 79,
    name: "aom-menu-WHQGL-color",
    alias: [],
    componentName: "IconAomMenuWHQGLColor",
    componentAlias: [],
    title: "奥姆菜单",
    category: "Menu",
    categoryCN: "菜单图标",
    author: "KSW",
    tag: ["菜单", "图标", "颜色", "设计"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.949Z",
  },
  {
    id: 80,
    name: "aom-menu-WWGL-color",
    alias: [],
    componentName: "IconAomMenuWWGLColor",
    componentAlias: [],
    title: "奥姆菜单",
    category: "Menu",
    categoryCN: "菜单",
    author: "KSW",
    tag: ["菜单", "WWGL", "颜色"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.949Z",
  },
  {
    id: 81,
    name: "aom-menu-XTSZ-color",
    alias: [],
    componentName: "IconAomMenuXTSZColor",
    componentAlias: [],
    title: "菜单选项",
    category: "UI",
    categoryCN: "用户界面元素",
    author: "KSW",
    tag: ["菜单", "选项", "颜色", "XTSZ"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.949Z",
  },
  {
    id: 82,
    name: "aom-menu-YHGL-color",
    alias: [],
    componentName: "IconAomMenuYHGLColor",
    componentAlias: [],
    title: "奥姆菜单",
    category: "Menu",
    categoryCN: "菜单",
    author: "KSW",
    tag: ["菜单", "颜色", "图标"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.949Z",
  },
  {
    id: 83,
    name: "aom-menu-YWBCZL-color",
    alias: [],
    componentName: "IconAomMenuYWBCZLColor",
    componentAlias: [],
    title: "菜单工具箱",
    category: "Tools",
    categoryCN: "工具",
    author: "KSW",
    tag: ["菜单", "工具箱", "工具"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.949Z",
  },
  {
    id: 84,
    name: "aom-menu-YYST-color",
    alias: [],
    componentName: "IconAomMenuYYSTColor",
    componentAlias: [],
    title: "菜单颜色",
    category: "UI",
    categoryCN: "用户界面元素",
    author: "KSW",
    tag: ["菜单", "颜色", "图标"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.949Z",
  },
  {
    id: 85,
    name: "aom-menu-ZBGL-color",
    alias: [],
    componentName: "IconAomMenuZBGLColor",
    componentAlias: [],
    title: "自动化管理菜单",
    category: "Automation",
    categoryCN: "自动化管理",
    author: "KSW",
    tag: ["自动化", "管理", "菜单", "综合管理", "颜色"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.949Z",
  },
  {
    id: 86,
    name: "aom-menu-ZBZXSZ-color",
    alias: [],
    componentName: "IconAomMenuZBZXSZColor",
    componentAlias: [],
    title: "",
    category: "Other",
    categoryCN: "其他",
    author: "KSW",
    tag: [],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.950Z",
  },
  {
    id: 87,
    name: "aom-menu-ZHCL-color",
    alias: [],
    componentName: "IconAomMenuZHCLColor",
    componentAlias: [],
    title: "菜单图标",
    category: "UI",
    categoryCN: "用户界面元素",
    author: "KSW",
    tag: ["菜单", "界面", "图标"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.950Z",
  },
  {
    id: 88,
    name: "aom-menu-ZHJG-color",
    alias: [],
    componentName: "IconAomMenuZHJGColor",
    componentAlias: [],
    title: "菜单",
    category: "Menu",
    categoryCN: "菜单",
    author: "KSW",
    tag: ["菜单", "中国", "颜色"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.950Z",
  },
  {
    id: 89,
    name: "aom-menu-ZXLS-color",
    alias: [],
    componentName: "IconAomMenuZXLSColor",
    componentAlias: [],
    title: "奥姆菜单",
    category: "Menu",
    categoryCN: "菜单",
    author: "KSW",
    tag: ["菜单", "自定义", "列表", "颜色"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.951Z",
  },
  {
    id: 90,
    name: "aom-menu-ZYSJ-color",
    alias: [],
    componentName: "IconAomMenuZYSJColor",
    componentAlias: [],
    title: "菜单",
    category: "Menu",
    categoryCN: "菜单",
    author: "KSW",
    tag: ["菜单", "自定义设置", "颜色"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.951Z",
  },
  {
    id: 91,
    name: "aom-menu-ZZFWQ-color",
    alias: [],
    componentName: "IconAomMenuZZFWQColor",
    componentAlias: [],
    title: "自动化菜单配置",
    category: "System",
    categoryCN: "系统配置",
    author: "KSW",
    tag: ["自动化", "菜单", "配置", "系统管理"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.951Z",
  },
  {
    id: 92,
    name: "application-color",
    alias: [],
    componentName: "IconApplicationColor",
    componentAlias: [],
    title: "",
    category: "Other",
    categoryCN: "其他",
    author: "KSW",
    tag: [],
    projectName: "base",
    modifiedTime: "2024-12-03T06:25:36.000Z",
  },
  {
    id: 93,
    name: "argument",
    alias: [],
    componentName: "IconArgument",
    componentAlias: [],
    title: "参数",
    category: "Programming",
    categoryCN: "编程",
    author: "KSW",
    tag: ["参数", "编程", "代码"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.952Z",
  },
  {
    id: 94,
    name: "arrow-back-up",
    alias: [],
    componentName: "IconArrowBackUp",
    componentAlias: [],
    title: "",
    category: "Other",
    categoryCN: "其他",
    author: "KSW",
    tag: [],
    projectName: "base",
    modifiedTime: "2024-12-03T07:57:46.000Z",
  },
  {
    id: 95,
    name: "arrow-bottom",
    alias: [],
    componentName: "IconArrowBottom",
    componentAlias: [],
    title: "向下箭头",
    category: "Navigation",
    categoryCN: "导航",
    author: "KSW",
    tag: ["箭头", "底部", "方向"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.952Z",
  },
  {
    id: 96,
    name: "arrow-forward-up",
    alias: [],
    componentName: "IconArrowForwardUp",
    componentAlias: [],
    title: "",
    category: "Other",
    categoryCN: "其他",
    author: "KSW",
    tag: [],
    projectName: "base",
    modifiedTime: "2024-12-03T07:57:46.000Z",
  },
  {
    id: 97,
    name: "arrow-left",
    alias: [],
    componentName: "IconArrowLeft",
    componentAlias: [],
    title: "左箭头",
    category: "Navigation",
    categoryCN: "导航",
    author: "KSW",
    tag: ["箭头", "方向", "返回", "导航"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.952Z",
  },
  {
    id: 98,
    name: "arrow-right",
    alias: [],
    componentName: "IconArrowRight",
    componentAlias: [],
    title: "右箭头",
    category: "Navigation",
    categoryCN: "导航",
    author: "KSW",
    tag: ["箭头", "方向", "右"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.952Z",
  },
  {
    id: 99,
    name: "arrow-to-left",
    alias: [],
    componentName: "IconArrowToLeft",
    componentAlias: [],
    title: "向左箭头",
    category: "Navigation",
    categoryCN: "导航",
    author: "KSW",
    tag: ["箭头", "方向", "左"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.952Z",
  },
  {
    id: 100,
    name: "arrow-to-right",
    alias: [],
    componentName: "IconArrowToRight",
    componentAlias: [],
    title: "向右箭头",
    category: "Navigation",
    categoryCN: "导航",
    author: "KSW",
    tag: ["箭头", "方向", "右"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.953Z",
  },
  {
    id: 101,
    name: "arrow-top",
    alias: [],
    componentName: "IconArrowTop",
    componentAlias: [],
    title: "向上箭头",
    category: "Directional",
    categoryCN: "方向图标",
    author: "KSW",
    tag: ["箭头", "向上", "方向"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.953Z",
  },
  {
    id: 102,
    name: "arrow-up-right",
    alias: [],
    componentName: "IconArrowUpRight",
    componentAlias: [],
    title: "向上右箭头",
    category: "Navigation",
    categoryCN: "导航",
    author: "KSW",
    tag: ["箭头", "方向", "导航", "向上", "右"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.953Z",
  },
  {
    id: 103,
    name: "arrows-exchange",
    alias: [],
    componentName: "IconArrowsExchange",
    componentAlias: [],
    title: "箭头交换",
    category: "Arrow direction",
    categoryCN: "箭头方向",
    author: "KSW",
    tag: ["交换", "转换"],
    projectName: "base",
    modifiedTime: "2025-01-13T12:09:51.091Z",
  },
  {
    id: 104,
    name: "backspace",
    alias: [],
    componentName: "IconBackspace",
    componentAlias: [],
    title: "",
    category: "Other",
    categoryCN: "其他",
    author: "KSW",
    tag: [],
    projectName: "base",
    modifiedTime: "2024-12-03T07:57:46.000Z",
  },
  {
    id: 105,
    name: "bot",
    alias: [],
    componentName: "IconBot",
    componentAlias: [],
    title: "机器人",
    category: "Artificial",
    categoryCN: "人工智能",
    author: "KSW",
    tag: ["自动化", "聊天机器人", "虚拟助手"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.954Z",
  },
  {
    id: 106,
    name: "c-type-autoit-color",
    alias: [],
    componentName: "IconCTypeAutoitColor",
    componentAlias: [],
    title: "C型自动色彩",
    category: "Color",
    categoryCN: "色彩工具",
    author: "KSW",
    tag: ["色彩", "自动色彩", "C型色彩"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.954Z",
  },
  {
    id: 107,
    name: "c-type-bat-color",
    alias: [],
    componentName: "IconCTypeBatColor",
    componentAlias: [],
    title: "C型蝙蝠颜色",
    category: "Animal",
    categoryCN: "动物",
    author: "KSW",
    tag: ["蝙蝠", "颜色", "C型"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.954Z",
  },
  {
    id: 108,
    name: "c-type-c-sharp-color",
    alias: [],
    componentName: "IconCTypeCSharpColor",
    componentAlias: [],
    title: "C型C尖锐颜色",
    category: "Technology",
    categoryCN: "科技",
    author: "KSW",
    tag: ["科技", "图标", "颜色"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.955Z",
  },
  {
    id: 109,
    name: "c-type-cn-color",
    alias: [],
    componentName: "IconCTypeCnColor",
    componentAlias: [],
    title: "中文类型颜色",
    category: "Color",
    categoryCN: "颜色",
    author: "KSW",
    tag: ["中文", "类型", "颜色"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.955Z",
  },
  {
    id: 110,
    name: "c-type-en-color",
    alias: [],
    componentName: "IconCTypeEnColor",
    componentAlias: [],
    title: "英文类型颜色",
    category: "Color",
    categoryCN: "颜色",
    author: "KSW",
    tag: ["颜色", "英文", "类型"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.955Z",
  },
  {
    id: 111,
    name: "c-type-fn-color",
    alias: [],
    componentName: "IconCTypeFnColor",
    componentAlias: [],
    title: "函数颜色类型",
    category: "Function",
    categoryCN: "函数颜色类型",
    author: "KSW",
    tag: ["函数", "颜色", "类型"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.956Z",
  },
  {
    id: 112,
    name: "c-type-JS-color",
    alias: [],
    componentName: "IconCTypeJSColor",
    componentAlias: [],
    title: "JavaScript颜色类型",
    category: "Programming",
    categoryCN: "编程",
    author: "KSW",
    tag: ["JavaScript", "颜色", "编程语言"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.954Z",
  },
  {
    id: 113,
    name: "c-type-lego-color",
    alias: [],
    componentName: "IconCTypeLegoColor",
    componentAlias: [],
    title: "C型乐高颜色",
    category: "Building",
    categoryCN: "积木",
    author: "KSW",
    tag: ["乐高", "积木", "颜色", "玩具"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.956Z",
  },
  {
    id: 114,
    name: "c-type-linuxshell-color",
    alias: [],
    componentName: "IconCTypeLinuxshellColor",
    componentAlias: [],
    title: "C类型Linux",
    category: "Programming",
    categoryCN: "编程工具",
    author: "KSW",
    tag: ["编程", "Linux", "Shell", "颜色"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.956Z",
  },
  {
    id: 115,
    name: "c-type-perl-color",
    alias: [],
    componentName: "IconCTypePerlColor",
    componentAlias: [],
    title: "C型Perl颜色",
    category: "Programming",
    categoryCN: "编程工具",
    author: "KSW",
    tag: ["编程", "Perl", "颜色", "工具"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.957Z",
  },
  {
    id: 116,
    name: "c-type-powershell-color",
    alias: [],
    componentName: "IconCTypePowershellColor",
    componentAlias: [],
    title: "C型PowerShell颜色",
    category: "Development",
    categoryCN: "开发工具",
    author: "KSW",
    tag: ["编程", "PowerShell", "颜色", "开发"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.957Z",
  },
  {
    id: 117,
    name: "c-type-python-color",
    alias: [],
    componentName: "IconCTypePythonColor",
    componentAlias: [],
    title: "C型Python颜色",
    category: "Programming",
    categoryCN: "编程工具",
    author: "KSW",
    tag: ["Python", "编程", "颜色", "开发工具"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.957Z",
  },
  {
    id: 118,
    name: "c-type-vbs-color",
    alias: [],
    componentName: "IconCTypeVbsColor",
    componentAlias: [],
    title: "VBS颜色类型",
    category: "Programming",
    categoryCN: "编程",
    author: "KSW",
    tag: ["VBS", "颜色", "编程语言"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.957Z",
  },
  {
    id: 119,
    name: "c-type-yaml-color",
    alias: [],
    componentName: "IconCTypeYamlColor",
    componentAlias: [],
    title: "C型YAML颜色",
    category: "Programming",
    categoryCN: "编程工具",
    author: "KSW",
    tag: ["编程", "YAML", "颜色", "代码"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.957Z",
  },
  {
    id: 120,
    name: "calendar-color",
    alias: [],
    componentName: "IconCalendarColor",
    componentAlias: [],
    title: "日历颜色",
    category: "Calendar",
    categoryCN: "日历",
    author: "KSW",
    tag: ["日历", "日期", "时间", "事件"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.957Z",
  },
  {
    id: 121,
    name: "card",
    alias: [],
    componentName: "IconCard",
    componentAlias: [],
    title: "卡片",
    category: "Finance",
    categoryCN: "金融",
    author: "KSW",
    tag: ["信用卡", "银行卡", "支付", "金融工具"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.958Z",
  },
  {
    id: 122,
    name: "chart-pie-color",
    alias: [],
    componentName: "IconChartPieColor",
    componentAlias: [],
    title: "彩色饼图",
    category: "Data",
    categoryCN: "数据可视化",
    author: "KSW",
    tag: ["图表", "饼图", "彩色"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.958Z",
  },
  {
    id: 123,
    name: "chart-pie",
    alias: [],
    componentName: "IconChartPie",
    componentAlias: [],
    title: "饼图",
    category: "Data",
    categoryCN: "数据可视化",
    author: "KSW",
    tag: ["图表", "数据", "分析", "展示"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.958Z",
  },
  {
    id: 124,
    name: "check-ed-color",
    alias: [],
    componentName: "IconCheckEdColor",
    componentAlias: [],
    title: "已选中颜色",
    category: "Status",
    categoryCN: "状态指示器",
    author: "KSW",
    tag: ["选中", "颜色", "确认", "完成"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.959Z",
  },
  {
    id: 125,
    name: "check-normal-color",
    alias: [],
    componentName: "IconCheckNormalColor",
    componentAlias: [],
    title: "正常颜色检查",
    category: "Verification",
    categoryCN: "验证",
    author: "KSW",
    tag: ["检查", "正常", "颜色"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.959Z",
  },
  {
    id: 126,
    name: "check-or-color",
    alias: [],
    componentName: "IconCheckOrColor",
    componentAlias: [],
    title: "检查或颜色",
    category: "Tools",
    categoryCN: "工具",
    author: "KSW",
    tag: ["检查", "颜色", "工具"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.959Z",
  },
  {
    id: 127,
    name: "check",
    alias: [],
    componentName: "IconCheck",
    componentAlias: [],
    title: "勾选",
    category: "Icons",
    categoryCN: "图标",
    author: "KSW",
    tag: ["勾选", "确认", "完成", "选择"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.960Z",
  },
  {
    id: 128,
    name: "clear",
    alias: [],
    componentName: "IconClear",
    componentAlias: [],
    title: "清除",
    category: "Action",
    categoryCN: "动作",
    author: "KSW",
    tag: ["清除", "删除", "取消"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.960Z",
  },
  {
    id: 129,
    name: "clear2",
    alias: [],
    componentName: "IconClear2",
    componentAlias: [],
    title: "清除2",
    category: "Cleaning",
    categoryCN: "清洁工具",
    author: "KSW",
    tag: ["清洁", "工具", "扫帚"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.960Z",
  },
  {
    id: 130,
    name: "clearDate",
    alias: [],
    componentName: "IconClearDate",
    componentAlias: [],
    title: "清除日期",
    category: "Date",
    categoryCN: "日期操作",
    author: "KSW",
    tag: ["日期", "清除", "时间管理"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.961Z",
  },
  {
    id: 131,
    name: "clipboard",
    alias: [],
    componentName: "IconClipboard",
    componentAlias: [],
    title: "",
    category: "Other",
    categoryCN: "其他",
    author: "KSW",
    tag: [],
    projectName: "base",
    modifiedTime: "2024-12-03T07:57:46.000Z",
  },
  {
    id: 132,
    name: "close",
    alias: [],
    componentName: "IconClose",
    componentAlias: [],
    title: "关闭",
    category: "Interface",
    categoryCN: "界面",
    author: "KSW",
    tag: ["关闭", "退出", "终止"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.961Z",
  },
  {
    id: 133,
    name: "Collect",
    alias: [],
    componentName: "IconCollect",
    componentAlias: [],
    title: "收藏",
    category: "User",
    categoryCN: "用户界面",
    author: "KSW",
    tag: ["收藏", "星形", "标记", "用户界面"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.928Z",
  },
  {
    id: 134,
    name: "copy",
    alias: [],
    componentName: "IconCopy",
    componentAlias: [],
    title: "复制",
    category: "Editing",
    categoryCN: "编辑工具",
    author: "KSW",
    tag: ["复制", "粘贴", "剪切"],
    projectName: "base",
    modifiedTime: "2024-12-03T07:57:46.000Z",
  },
  {
    id: 135,
    name: "cursor-pointer",
    alias: [],
    componentName: "IconCursorPointer",
    componentAlias: [],
    title: "光标指针",
    category: "Cursor",
    categoryCN: "光标",
    author: "KSW",
    tag: ["鼠标", "指针", "光标"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.962Z",
  },
  {
    id: 136,
    name: "cut",
    alias: [],
    componentName: "IconCut",
    componentAlias: [],
    title: "",
    category: "Other",
    categoryCN: "其他",
    author: "KSW",
    tag: [],
    projectName: "base",
    modifiedTime: "2024-12-03T07:57:46.000Z",
  },
  {
    id: 137,
    name: "date",
    alias: [],
    componentName: "IconDate",
    componentAlias: [],
    title: "日期",
    category: "Calendar",
    categoryCN: "日历",
    author: "KSW",
    tag: ["时间", "日期", "日历", "计划", "事件"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.962Z",
  },
  {
    id: 138,
    name: "delete",
    alias: [],
    componentName: "IconDelete",
    componentAlias: [],
    title: "删除",
    category: "Action",
    categoryCN: "动作",
    author: "KSW",
    tag: ["删除", "移除", "取消"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.962Z",
  },
  {
    id: 139,
    name: "dev-color",
    alias: [],
    componentName: "IconDevColor",
    componentAlias: [],
    title: "开发颜色",
    category: "Development",
    categoryCN: "开发工具",
    author: "KSW",
    tag: ["开发", "颜色", "工具"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.962Z",
  },
  {
    id: 140,
    name: "down-c",
    alias: [],
    componentName: "IconDownC",
    componentAlias: [],
    title: "向下箭头",
    category: "Direction",
    categoryCN: "方向",
    author: "KSW",
    tag: ["箭头", "向下", "方向"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.963Z",
  },
  {
    id: 141,
    name: "download",
    alias: [],
    componentName: "IconDownload",
    componentAlias: [],
    title: "",
    category: "Other",
    categoryCN: "其他",
    author: "KSW",
    tag: [],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.963Z",
  },
  {
    id: 142,
    name: "Drag",
    alias: [],
    componentName: "IconDrag",
    componentAlias: [],
    title: "拖动",
    category: "Interaction",
    categoryCN: "交互",
    author: "KSW",
    tag: ["拖拽", "移动", "操作"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.928Z",
  },
  {
    id: 143,
    name: "Edit",
    alias: [],
    componentName: "IconEdit",
    componentAlias: [],
    title: "编辑",
    category: "Editing",
    categoryCN: "编辑工具",
    author: "KSW",
    tag: ["编辑", "修改", "调整"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.928Z",
  },
  {
    id: 144,
    name: "EmptyBox",
    alias: [],
    componentName: "IconEmptyBox",
    componentAlias: [],
    title: "空盒子",
    category: "Containers",
    categoryCN: "容器",
    author: "KSW",
    tag: ["空", "盒子", "容器", "存储"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.929Z",
  },
  {
    id: 145,
    name: "enter-key-color",
    alias: [],
    componentName: "IconEnterKeyColor",
    componentAlias: [],
    title: "回车键-颜色",
    category: "Other",
    categoryCN: "其他",
    author: "KSW",
    tag: [],
    projectName: "base",
    modifiedTime: "2025-02-10T09:37:50.000Z",
  },
  {
    id: 146,
    name: "enter-key",
    alias: [],
    componentName: "IconEnterKey",
    componentAlias: [],
    title: "回车键",
    category: "Other",
    categoryCN: "其他",
    author: "KSW",
    tag: [],
    projectName: "base",
    modifiedTime: "2025-02-10T09:37:50.000Z",
  },
  {
    id: 147,
    name: "fall",
    alias: [],
    componentName: "IconFall",
    componentAlias: [],
    title: "秋天",
    category: "Season",
    categoryCN: "季节",
    author: "KSW",
    tag: ["秋天", "落叶", "丰收", "凉爽"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.963Z",
  },
  {
    id: 148,
    name: "file-add",
    alias: [],
    componentName: "IconFileAdd",
    componentAlias: [],
    title: "文件添加",
    category: "Document",
    categoryCN: "文档",
    author: "KSW",
    tag: ["文件", "添加", "文档", "新建"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.963Z",
  },
  {
    id: 149,
    name: "file-starred-color",
    alias: [],
    componentName: "IconFileStarredColor",
    componentAlias: [],
    title: "星标文件",
    category: "Documents",
    categoryCN: "文档",
    author: "KSW",
    tag: ["文件", "星标", "重要", "文档"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.964Z",
  },
  {
    id: 150,
    name: "file",
    alias: [],
    componentName: "IconFile",
    componentAlias: [],
    title: "文件",
    category: "Document",
    categoryCN: "文档",
    author: "KSW",
    tag: ["文件", "文档", "数据"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.964Z",
  },
  {
    id: 151,
    name: "filter-fill",
    alias: [],
    componentName: "IconFilterFill",
    componentAlias: [],
    title: "填充过滤器",
    category: "Tools",
    categoryCN: "工具",
    author: "KSW",
    tag: ["过滤器", "填充", "工具"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.964Z",
  },
  {
    id: 152,
    name: "filter",
    alias: [],
    componentName: "IconFilter",
    componentAlias: [],
    title: "过滤器",
    category: "Data",
    categoryCN: "数据处理",
    author: "KSW",
    tag: ["过滤", "筛选", "数据处理"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.964Z",
  },
  {
    id: 153,
    name: "flow-add",
    alias: [],
    componentName: "IconFlowAdd",
    componentAlias: [],
    title: "流程添加",
    category: "Process",
    categoryCN: "流程管理",
    author: "KSW",
    tag: ["流程", "添加", "管理", "工作流"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.965Z",
  },
  {
    id: 154,
    name: "flow-back",
    alias: [],
    componentName: "IconFlowBack",
    componentAlias: [],
    title: "回流",
    category: "Navigation",
    categoryCN: "导航",
    author: "KSW",
    tag: ["返回", "箭头", "导航", "界面"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.965Z",
  },
  {
    id: 155,
    name: "flow-batch-processing-color",
    alias: [],
    componentName: "IconFlowBatchProcessingColor",
    componentAlias: [],
    title: "批量处理流程",
    category: "Data",
    categoryCN: "数据处理",
    author: "KSW",
    tag: ["批量处理", "流程", "彩色", "数据", "处理"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.965Z",
  },
  {
    id: 156,
    name: "flow-check-color",
    alias: [],
    componentName: "IconFlowCheckColor",
    componentAlias: [],
    title: "流程检查颜色",
    category: "Process",
    categoryCN: "流程管理",
    author: "KSW",
    tag: ["流程", "检查", "颜色"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.965Z",
  },
  {
    id: 157,
    name: "flow-component-color",
    alias: [],
    componentName: "IconFlowComponentColor",
    componentAlias: [],
    title: "流动组件颜色",
    category: "UI",
    categoryCN: "用户界面组件",
    author: "KSW",
    tag: ["颜色", "组件", "流动", "设计"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.966Z",
  },
  {
    id: 158,
    name: "flow-controls-color",
    alias: [],
    componentName: "IconFlowControlsColor",
    componentAlias: [],
    title: "流程控制颜色",
    category: "Flow",
    categoryCN: "流程控制",
    author: "KSW",
    tag: ["流程", "控制", "颜色"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.966Z",
  },
  {
    id: 159,
    name: "flow-end-color",
    alias: [],
    componentName: "IconFlowEndColor",
    componentAlias: [],
    title: "流程结束颜色",
    category: "Flow",
    categoryCN: "流程",
    author: "KSW",
    tag: ["流程", "结束", "颜色"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.966Z",
  },
  {
    id: 160,
    name: "flow-end",
    alias: [],
    componentName: "IconFlowEnd",
    componentAlias: [],
    title: "流程结束",
    category: "Process",
    categoryCN: "流程",
    author: "KSW",
    tag: ["流程", "结束", "标志"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.966Z",
  },
  {
    id: 161,
    name: "flow-if-color",
    alias: [],
    componentName: "IconFlowIfColor",
    componentAlias: [],
    title: "流程判断颜色",
    category: "Flow",
    categoryCN: "流程控制",
    author: "KSW",
    tag: ["流程", "判断", "颜色"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.966Z",
  },
  {
    id: 162,
    name: "flow-nested-color",
    alias: [],
    componentName: "IconFlowNestedColor",
    componentAlias: [],
    title: "流动嵌套颜色",
    category: "Design",
    categoryCN: "设计元素",
    author: "KSW",
    tag: ["流动", "嵌套", "颜色", "设计"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.966Z",
  },
  {
    id: 163,
    name: "flow-nested",
    alias: [],
    componentName: "IconFlowNested",
    componentAlias: [],
    title: "流动嵌套",
    category: "Design",
    categoryCN: "设计元素",
    author: "KSW",
    tag: ["流动", "嵌套", "设计"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.967Z",
  },
  {
    id: 164,
    name: "flow-quote-color",
    alias: [],
    componentName: "IconFlowQuoteColor",
    componentAlias: [],
    title: "流动引文颜色",
    category: "Design",
    categoryCN: "设计元素",
    author: "KSW",
    tag: ["流动", "引文", "颜色", "设计"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.967Z",
  },
  {
    id: 165,
    name: "flow-start-color",
    alias: [],
    componentName: "IconFlowStartColor",
    componentAlias: [],
    title: "流动开始颜色",
    category: "Color",
    categoryCN: "颜色",
    author: "KSW",
    tag: ["流动", "开始", "颜色"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.967Z",
  },
  {
    id: 166,
    name: "flow-start",
    alias: [],
    componentName: "IconFlowStart",
    componentAlias: [],
    title: "流程开始",
    category: "Process",
    categoryCN: "流程",
    author: "KSW",
    tag: ["流程", "开始", "启动"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.967Z",
  },
  {
    id: 167,
    name: "flow-tips-color",
    alias: [],
    componentName: "IconFlowTipsColor",
    componentAlias: [],
    title: "流动提示颜色",
    category: "Design",
    categoryCN: "设计元素",
    author: "KSW",
    tag: ["流动", "提示", "颜色", "设计"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.967Z",
  },
  {
    id: 168,
    name: "flow-toolBox",
    alias: [],
    componentName: "IconFlowToolBox",
    componentAlias: [],
    title: "流程工具箱",
    category: "Development",
    categoryCN: "开发工具",
    author: "KSW",
    tag: ["流程", "工具", "开发"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.968Z",
  },
  {
    id: 169,
    name: "flow",
    alias: [],
    componentName: "IconFlow",
    componentAlias: [],
    title: "流程",
    category: "Process",
    categoryCN: "流程图",
    author: "KSW",
    tag: ["流程", "图表", "结构"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.968Z",
  },
  {
    id: 170,
    name: "fn-add",
    alias: [],
    componentName: "IconFnAdd",
    componentAlias: [],
    title: "添加功能",
    category: "Function",
    categoryCN: "功能",
    author: "KSW",
    tag: ["添加", "功能", "操作"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.968Z",
  },
  {
    id: 171,
    name: "fn",
    alias: [],
    componentName: "IconFn",
    componentAlias: [],
    title: "函数",
    category: "Mathematics",
    categoryCN: "数学",
    author: "KSW",
    tag: ["函数", "数学", "公式"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.969Z",
  },
  {
    id: 172,
    name: "fold-down",
    alias: [],
    componentName: "IconFoldDown",
    componentAlias: [],
    title: "",
    category: "Other",
    categoryCN: "其他",
    author: "KSW",
    tag: [],
    projectName: "base",
    modifiedTime: "2024-12-03T07:57:46.000Z",
  },
  {
    id: 173,
    name: "fold-up",
    alias: [],
    componentName: "IconFoldUp",
    componentAlias: [],
    title: "",
    category: "Other",
    categoryCN: "其他",
    author: "KSW",
    tag: [],
    projectName: "base",
    modifiedTime: "2024-12-03T07:57:46.000Z",
  },
  {
    id: 174,
    name: "fold",
    alias: [],
    componentName: "IconFold",
    componentAlias: [],
    title: "折叠",
    category: "Navigation",
    categoryCN: "导航",
    author: "KSW",
    tag: ["折叠", "展开", "箭头", "方向"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.969Z",
  },
  {
    id: 175,
    name: "folder-add",
    alias: [],
    componentName: "IconFolderAdd",
    componentAlias: [],
    title: "添加文件夹",
    category: "File",
    categoryCN: "文件管理",
    author: "KSW",
    tag: ["文件夹", "添加", "新建"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.969Z",
  },
  {
    id: 176,
    name: "folder-close",
    alias: [],
    componentName: "IconFolderClose",
    componentAlias: [],
    title: "关闭文件夹",
    category: "File",
    categoryCN: "文件管理",
    author: "KSW",
    tag: ["文件夹", "关闭", "文档", "管理"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.970Z",
  },
  {
    id: 177,
    name: "folder-flash-color",
    alias: [],
    componentName: "IconFolderFlashColor",
    componentAlias: [],
    title: "文件夹闪存-颜色",
    category: "Other",
    categoryCN: "其他",
    author: "KSW",
    tag: [],
    projectName: "base",
    modifiedTime: "2025-02-10T09:37:50.000Z",
  },
  {
    id: 178,
    name: "folder-flash",
    alias: [],
    componentName: "IconFolderFlash",
    componentAlias: [],
    title: "文件夹闪存",
    category: "Other",
    categoryCN: "其他",
    author: "KSW",
    tag: [],
    projectName: "base",
    modifiedTime: "2025-02-10T09:37:50.000Z",
  },
  {
    id: 179,
    name: "folder-open",
    alias: [],
    componentName: "IconFolderOpen",
    componentAlias: [],
    title: "打开文件夹",
    category: "File",
    categoryCN: "文件管理",
    author: "KSW",
    tag: ["文件夹", "打开", "文档", "存储"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.970Z",
  },
  {
    id: 180,
    name: "forbid",
    alias: [],
    componentName: "IconForbid",
    componentAlias: [],
    title: "",
    category: "Other",
    categoryCN: "其他",
    author: "KSW",
    tag: [],
    projectName: "base",
    modifiedTime: "2024-12-03T07:57:46.000Z",
  },
  {
    id: 181,
    name: "full-screen",
    alias: [],
    componentName: "IconFullScreen",
    componentAlias: [],
    title: "全屏",
    category: "Display",
    categoryCN: "显示",
    author: "KSW",
    tag: ["全屏", "显示", "屏幕"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.970Z",
  },
  {
    id: 182,
    name: "function",
    alias: [],
    componentName: "IconFunction",
    componentAlias: [],
    title: "",
    category: "Other",
    categoryCN: "其他",
    author: "KSW",
    tag: [],
    projectName: "base",
    modifiedTime: "2024-12-17T02:42:14.970Z",
  },
  {
    id: 183,
    name: "GlobalOperation",
    alias: [],
    componentName: "IconGlobalOperation",
    componentAlias: [],
    title: "全球操作",
    category: "International",
    categoryCN: "国际服务",
    author: "KSW",
    tag: ["全球", "操作", "国际", "服务"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.929Z",
  },
  {
    id: 184,
    name: "hard-drive-color",
    alias: [],
    componentName: "IconHardDriveColor",
    componentAlias: [],
    title: "彩色硬盘",
    category: "Storage",
    categoryCN: "存储设备",
    author: "KSW",
    tag: ["硬盘", "存储", "彩色"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.970Z",
  },
  {
    id: 185,
    name: "hide",
    alias: [],
    componentName: "IconHide",
    componentAlias: [],
    title: "隐藏",
    category: "Visibility",
    categoryCN: "可见性",
    author: "KSW",
    tag: ["隐藏", "不可见", "遮挡"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.970Z",
  },
  {
    id: 186,
    name: "icon-def",
    alias: [],
    componentName: "IconIconDef",
    componentAlias: [],
    title: "图标定义",
    category: "Design",
    categoryCN: "设计元素",
    author: "KSW",
    tag: ["图标", "设计", "元素", "定义"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.971Z",
  },
  {
    id: 187,
    name: "ide-pause",
    alias: [],
    componentName: "IconIdePause",
    componentAlias: [],
    title: "IDE暂停",
    category: "Development",
    categoryCN: "开发工具",
    author: "KSW",
    tag: ["编程", "IDE", "暂停", "开发", "工具"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.971Z",
  },
  {
    id: 188,
    name: "ide-play",
    alias: [],
    componentName: "IconIdePlay",
    componentAlias: [],
    title: "IDE播放",
    category: "Development",
    categoryCN: "开发工具",
    author: "KSW",
    tag: ["编程", "开发", "IDE", "播放"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.971Z",
  },
  {
    id: 189,
    name: "ide-refresh",
    alias: [],
    componentName: "IconIdeRefresh",
    componentAlias: [],
    title: "IDE刷新",
    category: "Development",
    categoryCN: "开发工具",
    author: "KSW",
    tag: ["IDE", "刷新", "开发", "工具"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.971Z",
  },
  {
    id: 190,
    name: "ide-stop",
    alias: [],
    componentName: "IconIdeStop",
    componentAlias: [],
    title: "IDE停止",
    category: "Development",
    categoryCN: "开发工具",
    author: "KSW",
    tag: ["IDE", "停止", "开发", "编程"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.971Z",
  },
  {
    id: 191,
    name: "IP",
    alias: [],
    componentName: "IconIP",
    componentAlias: [],
    title: "IP地址",
    category: "Network",
    categoryCN: "网络",
    author: "KSW",
    tag: ["互联网", "地址", "网络", "连接"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.929Z",
  },
  {
    id: 192,
    name: "item-def-color",
    alias: [],
    componentName: "IconItemDefColor",
    componentAlias: [],
    title: "默认颜色项",
    category: "Color",
    categoryCN: "颜色管理",
    author: "KSW",
    tag: ["颜色", "默认", "图标", "设计"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.972Z",
  },
  {
    id: 193,
    name: "item-remove",
    alias: [],
    componentName: "IconItemRemove",
    componentAlias: [],
    title: "",
    category: "Other",
    categoryCN: "其他",
    author: "KSW",
    tag: [],
    projectName: "base",
    modifiedTime: "2024-12-19T08:45:39.535Z",
  },
  {
    id: 194,
    name: "left-menu-display",
    alias: [],
    componentName: "IconLeftMenuDisplay",
    componentAlias: [],
    title: "左侧菜单显示",
    category: "Navigation",
    categoryCN: "导航",
    author: "KSW",
    tag: ["菜单", "显示", "左侧"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.972Z",
  },
  {
    id: 195,
    name: "line",
    alias: [],
    componentName: "IconLine",
    componentAlias: [],
    title: "线条",
    category: "Design",
    categoryCN: "设计",
    author: "KSW",
    tag: ["线条", "设计元素", "图形"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.972Z",
  },
  {
    id: 196,
    name: "list-close",
    alias: [],
    componentName: "IconListClose",
    componentAlias: [],
    title: "列表关闭",
    category: "List",
    categoryCN: "列表管理",
    author: "KSW",
    tag: ["列表", "关闭", "管理"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.972Z",
  },
  {
    id: 197,
    name: "list-open",
    alias: [],
    componentName: "IconListOpen",
    componentAlias: [],
    title: "列表打开",
    category: "Navigation",
    categoryCN: "导航",
    author: "KSW",
    tag: ["列表", "打开", "导航", "下拉"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.973Z",
  },
  {
    id: 198,
    name: "list-search",
    alias: [],
    componentName: "IconListSearch",
    componentAlias: [],
    title: "列表搜索",
    category: "Edit",
    categoryCN: "编辑",
    author: "KSW",
    tag: ["列表", "搜索", "查看"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.973Z",
  },
  {
    id: 199,
    name: "loading",
    alias: [],
    componentName: "IconLoading",
    componentAlias: [],
    title: "加载中",
    category: "Progress",
    categoryCN: "进度",
    author: "KSW",
    tag: ["加载", "缓冲", "等待", "进度条"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.973Z",
  },
  {
    id: 200,
    name: "lock",
    alias: [],
    componentName: "IconLock",
    componentAlias: [],
    title: "锁",
    category: "Security",
    categoryCN: "安全",
    author: "KSW",
    tag: ["安全", "保护", "隐私"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.973Z",
  },
  {
    id: 201,
    name: "locked",
    alias: [],
    componentName: "IconLocked",
    componentAlias: [],
    title: "锁定",
    category: "Security",
    categoryCN: "安全",
    author: "KSW",
    tag: ["锁定", "安全", "保护", "隐私"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.974Z",
  },
  {
    id: 202,
    name: "logout",
    alias: [],
    componentName: "IconLogout",
    componentAlias: [],
    title: "登出",
    category: "User",
    categoryCN: "用户界面",
    author: "KSW",
    tag: ["退出", "注销", "离开"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.974Z",
  },
  {
    id: 203,
    name: "mail-color",
    alias: [],
    componentName: "IconMailColor",
    componentAlias: [],
    title: "邮件颜色",
    category: "Other",
    categoryCN: "其他",
    author: "KSW",
    tag: [],
    projectName: "base",
    modifiedTime: "2025-02-10T09:37:50.000Z",
  },
  {
    id: 204,
    name: "mail",
    alias: [],
    componentName: "IconMail",
    componentAlias: [],
    title: "邮件",
    category: "Other",
    categoryCN: "其他",
    author: "KSW",
    tag: [],
    projectName: "base",
    modifiedTime: "2025-02-10T09:37:50.000Z",
  },
  {
    id: 205,
    name: "medal-1",
    alias: [],
    componentName: "IconMedal1",
    componentAlias: [],
    title: "奖章1",
    category: "Awards",
    categoryCN: "奖项",
    author: "KSW",
    tag: ["奖章", "荣誉", "成就"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.974Z",
  },
  {
    id: 206,
    name: "medal-2",
    alias: [],
    componentName: "IconMedal2",
    componentAlias: [],
    title: "奖章",
    category: "Awards",
    categoryCN: "奖项",
    author: "KSW",
    tag: ["奖章", "荣誉", "成就"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.974Z",
  },
  {
    id: 207,
    name: "medal-3",
    alias: [],
    componentName: "IconMedal3",
    componentAlias: [],
    title: "",
    category: "Other",
    categoryCN: "其他",
    author: "KSW",
    tag: [],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.975Z",
  },
  {
    id: 208,
    name: "menu-collect",
    alias: [],
    componentName: "IconMenuCollect",
    componentAlias: [],
    title: "菜单收藏",
    category: "Navigation",
    categoryCN: "导航",
    author: "KSW",
    tag: ["菜单", "收藏", "导航"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.975Z",
  },
  {
    id: 209,
    name: "menu-collected",
    alias: [],
    componentName: "IconMenuCollected",
    componentAlias: [],
    title: "菜单收藏",
    category: "Navigation",
    categoryCN: "导航",
    author: "KSW",
    tag: ["菜单", "收藏", "导航"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.975Z",
  },
  {
    id: 210,
    name: "menu-def-color",
    alias: [],
    componentName: "IconMenuDefColor",
    componentAlias: [],
    title: "菜单默认颜色",
    category: "UI",
    categoryCN: "用户界面元素",
    author: "KSW",
    tag: ["菜单", "颜色", "默认"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.975Z",
  },
  {
    id: 211,
    name: "Message",
    alias: [],
    componentName: "IconMessage",
    componentAlias: [],
    title: "消息",
    category: "Communication",
    categoryCN: "通信",
    author: "KSW",
    tag: ["消息", "通信", "通知", "提醒"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.930Z",
  },
  {
    id: 212,
    name: "mode-expression-color",
    alias: [],
    componentName: "IconModeExpressionColor",
    componentAlias: [],
    title: "",
    category: "Other",
    categoryCN: "其他",
    author: "KSW",
    tag: [],
    projectName: "base",
    modifiedTime: "2024-12-03T06:22:48.947Z",
  },
  {
    id: 213,
    name: "mode-expression",
    alias: [],
    componentName: "IconModeExpression",
    componentAlias: [],
    title: "",
    category: "Other",
    categoryCN: "其他",
    author: "KSW",
    tag: [],
    projectName: "base",
    modifiedTime: "2024-12-03T06:22:48.947Z",
  },
  {
    id: 214,
    name: "more",
    alias: [],
    componentName: "IconMore",
    componentAlias: [],
    title: "更多",
    category: "Navigation",
    categoryCN: "导航",
    author: "KSW",
    tag: ["更多选项", "菜单", "扩展"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.976Z",
  },
  {
    id: 215,
    name: "organization",
    alias: [],
    componentName: "IconOrganization",
    componentAlias: [],
    title: "组织",
    category: "Business",
    categoryCN: "商业",
    author: "KSW",
    tag: ["公司", "机构", "团队"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.976Z",
  },
  {
    id: 216,
    name: "patch-color",
    alias: [],
    componentName: "IconPatchColor",
    componentAlias: [],
    title: "补丁颜色",
    category: "Design",
    categoryCN: "设计工具",
    author: "KSW",
    tag: ["补丁", "颜色", "设计"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.976Z",
  },
  {
    id: 217,
    name: "patch-set-color",
    alias: [],
    componentName: "IconPatchSetColor",
    componentAlias: [],
    title: "补丁设置颜色",
    category: "Development",
    categoryCN: "开发工具",
    author: "KSW",
    tag: ["补丁", "颜色设置", "开发工具"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.976Z",
  },
  {
    id: 218,
    name: "personnel",
    alias: [],
    componentName: "IconPersonnel",
    componentAlias: [],
    title: "人员",
    category: "Human",
    categoryCN: "人力资源",
    author: "KSW",
    tag: ["员工", "人事", "管理", "招聘"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.977Z",
  },
  {
    id: 219,
    name: "play",
    alias: [],
    componentName: "IconPlay",
    componentAlias: [],
    title: "",
    category: "Other",
    categoryCN: "其他",
    author: "KSW",
    tag: [],
    projectName: "base",
    modifiedTime: "2024-12-03T07:57:46.000Z",
  },
  {
    id: 220,
    name: "plug-in-360-color",
    alias: [],
    componentName: "IconPlugIn360Color",
    componentAlias: [],
    title: "360度彩色插件",
    category: "Software",
    categoryCN: "软件工具",
    author: "KSW",
    tag: ["插件", "360度", "彩色", "软件"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.977Z",
  },
  {
    id: 221,
    name: "plug-in-Chrome-color",
    alias: [],
    componentName: "IconPlugInChromeColor",
    componentAlias: [],
    title: "插件",
    category: "Browser",
    categoryCN: "浏览器插件",
    author: "KSW",
    tag: ["插件", "Chrome", "颜色"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.977Z",
  },
  {
    id: 222,
    name: "plug-in-Edge-color",
    alias: [],
    componentName: "IconPlugInEdgeColor",
    componentAlias: [],
    title: "插件边缘颜色",
    category: "Software",
    categoryCN: "软件工具",
    author: "KSW",
    tag: ["插件", "边缘", "颜色", "设计", "工具"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.977Z",
  },
  {
    id: 223,
    name: "plug-in-excel-color",
    alias: [],
    componentName: "IconPlugInExcelColor",
    componentAlias: [],
    title: "Excel插件颜色",
    category: "Software",
    categoryCN: "软件工具",
    author: "KSW",
    tag: ["Excel", "插件", "颜色"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.978Z",
  },
  {
    id: 224,
    name: "plug-in-Firefox-color",
    alias: [],
    componentName: "IconPlugInFirefoxColor",
    componentAlias: [],
    title: "火狐插件颜色",
    category: "Browser",
    categoryCN: "浏览器插件",
    author: "KSW",
    tag: ["火狐", "插件", "颜色"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.977Z",
  },
  {
    id: 225,
    name: "plug-in-image-color",
    alias: [],
    componentName: "IconPlugInImageColor",
    componentAlias: [],
    title: "插件图像颜色",
    category: "Image",
    categoryCN: "图像处理",
    author: "KSW",
    tag: ["插件", "图像", "颜色"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.978Z",
  },
  {
    id: 226,
    name: "plug-in-java-color",
    alias: [],
    componentName: "IconPlugInJavaColor",
    componentAlias: [],
    title: "插件Java颜色",
    category: "Development",
    categoryCN: "开发工具",
    author: "KSW",
    tag: ["插件", "Java", "颜色", "开发工具"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.979Z",
  },
  {
    id: 227,
    name: "plug-in-Mail-color",
    alias: [],
    componentName: "IconPlugInMailColor",
    componentAlias: [],
    title: "插件邮件颜色",
    category: "Email",
    categoryCN: "电子邮件插件",
    author: "KSW",
    tag: ["邮件", "插件", "颜色"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.978Z",
  },
  {
    id: 228,
    name: "plug-in-Net-color-2",
    alias: [],
    componentName: "IconPlugInNetColor2",
    componentAlias: [],
    title: "插件网络颜色2",
    category: "Software",
    categoryCN: "软件工具",
    author: "KSW",
    tag: ["插件", "网络", "颜色", "工具"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.978Z",
  },
  {
    id: 229,
    name: "plug-in-Net-color",
    alias: [],
    componentName: "IconPlugInNetColor",
    componentAlias: [],
    title: "插件",
    category: "Software",
    categoryCN: "软件开发",
    author: "KSW",
    tag: ["插件", "Net", "颜色"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.978Z",
  },
  {
    id: 230,
    name: "plug-in-OCR-color",
    alias: [],
    componentName: "IconPlugInOCRColor",
    componentAlias: [],
    title: "插件OCR颜色识别",
    category: "Image",
    categoryCN: "图像处理",
    author: "KSW",
    tag: ["OCR", "颜色识别", "插件"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.978Z",
  },
  {
    id: 231,
    name: "plug-in-pdf-color",
    alias: [],
    componentName: "IconPlugInPdfColor",
    componentAlias: [],
    title: "插件PDF颜色",
    category: "Software",
    categoryCN: "软件工具",
    author: "KSW",
    tag: ["插件", "PDF", "颜色"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.979Z",
  },
  {
    id: 232,
    name: "plug-in-sogou-color",
    alias: [],
    componentName: "IconPlugInSogouColor",
    componentAlias: [],
    title: "搜狗插件颜色",
    category: "Software",
    categoryCN: "软件工具",
    author: "KSW",
    tag: ["插件", "搜狗", "颜色"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.979Z",
  },
  {
    id: 233,
    name: "plug-in-SSL-color",
    alias: [],
    componentName: "IconPlugInSSLColor",
    componentAlias: [],
    title: "插件SSL颜色",
    category: "Security",
    categoryCN: "安全",
    author: "KSW",
    tag: ["插件", "SSL", "颜色"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.978Z",
  },
  {
    id: 234,
    name: "plug-in-text-color",
    alias: [],
    componentName: "IconPlugInTextColor",
    componentAlias: [],
    title: "插件文本颜色",
    category: "Text",
    categoryCN: "文本编辑",
    author: "KSW",
    tag: ["插件", "文本", "颜色", "编辑"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.979Z",
  },
  {
    id: 235,
    name: "portfolio",
    alias: [],
    componentName: "IconPortfolio",
    componentAlias: [],
    title: "投资组合",
    category: "Finance",
    categoryCN: "金融",
    author: "KSW",
    tag: ["投资", "组合", "金融", "管理"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.979Z",
  },
  {
    id: 236,
    name: "project-logo-gf-color",
    alias: [],
    componentName: "IconProjectLogoGfColor",
    componentAlias: [],
    title: "项目标志GF彩色",
    category: "Logo",
    categoryCN: "标志",
    author: "KSW",
    tag: ["项目", "标志", "彩色", "设计"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.980Z",
  },
  {
    id: 237,
    name: "Question-line",
    alias: [],
    componentName: "IconQuestionLine",
    componentAlias: [],
    title: "问号",
    category: "Symbols",
    categoryCN: "符号",
    author: "KSW",
    tag: ["问题", "帮助", "询问", "信息"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.930Z",
  },
  {
    id: 238,
    name: "question",
    alias: [],
    componentName: "IconQuestion",
    componentAlias: [],
    title: "问题",
    category: "Help",
    categoryCN: "帮助",
    author: "KSW",
    tag: ["问题", "帮助", "询问"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.980Z",
  },
  {
    id: 239,
    name: "ranking-color",
    alias: [],
    componentName: "IconRankingColor",
    componentAlias: [],
    title: "排名颜色",
    category: "Color",
    categoryCN: "颜色",
    author: "KSW",
    tag: ["排名", "颜色", "图标"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.980Z",
  },
  {
    id: 240,
    name: "ranking",
    alias: [],
    componentName: "IconRanking",
    componentAlias: [],
    title: "排名",
    category: "Data",
    categoryCN: "数据分析",
    author: "KSW",
    tag: ["排名", "数据", "分析", "图表"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.980Z",
  },
  {
    id: 241,
    name: "re-screen",
    alias: [],
    componentName: "IconReScreen",
    componentAlias: [],
    title: "重新筛选",
    category: "Data",
    categoryCN: "数据处理",
    author: "KSW",
    tag: ["筛选", "数据", "处理", "分析"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.981Z",
  },
  {
    id: 242,
    name: "refresh",
    alias: [],
    componentName: "IconRefresh",
    componentAlias: [],
    title: "刷新",
    category: "Action",
    categoryCN: "动作",
    author: "KSW",
    tag: ["刷新", "更新", "重新加载"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.981Z",
  },
  {
    id: 243,
    name: "reset",
    alias: [],
    componentName: "IconReset",
    componentAlias: [],
    title: "重置",
    category: "System",
    categoryCN: "系统",
    author: "KSW",
    tag: ["重置", "恢复", "初始化"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.981Z",
  },
  {
    id: 244,
    name: "rise",
    alias: [],
    componentName: "IconRise",
    componentAlias: [],
    title: "",
    category: "Other",
    categoryCN: "其他",
    author: "KSW",
    tag: [],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.981Z",
  },
  {
    id: 245,
    name: "save",
    alias: [],
    componentName: "IconSave",
    componentAlias: [],
    title: "保存",
    category: "File",
    categoryCN: "文件管理",
    author: "KSW",
    tag: ["保存", "文件", "存储"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.981Z",
  },
  {
    id: 246,
    name: "scan",
    alias: [],
    componentName: "IconScan",
    componentAlias: [],
    title: "扫描",
    category: "Technology",
    categoryCN: "科技",
    author: "KSW",
    tag: ["扫描仪", "条形码", "二维码"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.981Z",
  },
  {
    id: 247,
    name: "scrip-color",
    alias: [],
    componentName: "IconScripColor",
    componentAlias: [],
    title: "脚本颜色",
    category: "Development",
    categoryCN: "开发工具",
    author: "KSW",
    tag: ["编程", "代码", "颜色"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.982Z",
  },
  {
    id: 248,
    name: "scrip",
    alias: [],
    componentName: "IconScrip",
    componentAlias: [],
    title: "脚本",
    category: "Programming",
    categoryCN: "编程",
    author: "KSW",
    tag: ["脚本", "编程", "代码"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.982Z",
  },
  {
    id: 249,
    name: "seal",
    alias: [],
    componentName: "IconSeal",
    componentAlias: [],
    title: "印章",
    category: "Stationery",
    categoryCN: "文具",
    author: "KSW",
    tag: ["印章", "办公用品", "文具"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.982Z",
  },
  {
    id: 250,
    name: "search",
    alias: [],
    componentName: "IconSearch",
    componentAlias: [],
    title: "搜索",
    category: "Navigation",
    categoryCN: "导航",
    author: "KSW",
    tag: ["搜索", "放大镜", "查找"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.982Z",
  },
  {
    id: 251,
    name: "setting-animation",
    alias: [],
    componentName: "IconSettingAnimation",
    componentAlias: [],
    title: "设置动画",
    category: "Design",
    categoryCN: "设计工具",
    author: "KSW",
    tag: ["设置", "动画", "设计", "工具"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.983Z",
  },
  {
    id: 252,
    name: "setting-fill",
    alias: [],
    componentName: "IconSettingFill",
    componentAlias: [],
    title: "设置填充",
    category: "Tools",
    categoryCN: "工具",
    author: "KSW",
    tag: ["设置", "配置", "选项", "工具"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.983Z",
  },
  {
    id: 253,
    name: "setting",
    alias: [],
    componentName: "IconSetting",
    componentAlias: [],
    title: "设置",
    category: "System",
    categoryCN: "系统工具",
    author: "KSW",
    tag: ["设置", "配置", "系统管理"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.983Z",
  },
  {
    id: 254,
    name: "show",
    alias: [],
    componentName: "IconShow",
    componentAlias: [],
    title: "显示",
    category: "Visibility",
    categoryCN: "可见性",
    author: "KSW",
    tag: ["显示", "可见", "视觉"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.984Z",
  },
  {
    id: 255,
    name: "size-controls",
    alias: [],
    componentName: "IconSizeControls",
    componentAlias: [],
    title: "大小控制",
    category: "Edit",
    categoryCN: "编辑",
    author: "KSW",
    tag: ["控制"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.984Z",
  },
  {
    id: 256,
    name: "sort-bottom",
    alias: [],
    componentName: "IconSortBottom",
    componentAlias: [],
    title: "底部排序",
    category: "Sorting",
    categoryCN: "排序",
    author: "KSW",
    tag: ["排序", "底部", "图标"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.984Z",
  },
  {
    id: 257,
    name: "sort-down",
    alias: [],
    componentName: "IconSortDown",
    componentAlias: [],
    title: "向下排序",
    category: "Sorting",
    categoryCN: "排序",
    author: "KSW",
    tag: ["排序", "向下", "箭头"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.984Z",
  },
  {
    id: 258,
    name: "sort-top",
    alias: [],
    componentName: "IconSortTop",
    componentAlias: [],
    title: "顶部排序",
    category: "Sorting",
    categoryCN: "排序",
    author: "KSW",
    tag: ["排序", "顶部", "图标"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.985Z",
  },
  {
    id: 259,
    name: "sort-up",
    alias: [],
    componentName: "IconSortUp",
    componentAlias: [],
    title: "排序上升",
    category: "Sorting",
    categoryCN: "排序",
    author: "KSW",
    tag: ["排序", "上升", "箭头"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.985Z",
  },
  {
    id: 260,
    name: "status-403",
    alias: [],
    componentName: "IconStatus403",
    componentAlias: [],
    title: "状态",
    category: "HTTP",
    categoryCN: "HTTP状态",
    author: "KSW",
    tag: ["错误", "访问被拒绝", "403"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.985Z",
  },
  {
    id: 261,
    name: "status-404",
    alias: [],
    componentName: "IconStatus404",
    componentAlias: [],
    title: "状态",
    category: "Error",
    categoryCN: "错误页面",
    author: "KSW",
    tag: ["错误", "404", "未找到"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.985Z",
  },
  {
    id: 262,
    name: "status-500",
    alias: [],
    componentName: "IconStatus500",
    componentAlias: [],
    title: "状态500",
    category: "Error",
    categoryCN: "错误",
    author: "KSW",
    tag: ["错误", "500", "服务器错误"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.985Z",
  },
  {
    id: 263,
    name: "status-danger",
    alias: [],
    componentName: "IconStatusDanger",
    componentAlias: [],
    title: "危险状态",
    category: "Status",
    categoryCN: "状态指示器",
    author: "KSW",
    tag: ["警告", "错误", "危险", "注意"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.986Z",
  },
  {
    id: 264,
    name: "status-def",
    alias: [],
    componentName: "IconStatusDef",
    componentAlias: [],
    title: "",
    category: "Other",
    categoryCN: "其他",
    author: "KSW",
    tag: [],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.986Z",
  },
  {
    id: 265,
    name: "status-empty-color",
    alias: [],
    componentName: "IconStatusEmptyColor",
    componentAlias: [],
    title: "",
    category: "Other",
    categoryCN: "其他",
    author: "KSW",
    tag: [],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.986Z",
  },
  {
    id: 266,
    name: "status-empty",
    alias: [],
    componentName: "IconStatusEmpty",
    componentAlias: [],
    title: "状态空",
    category: "Status",
    categoryCN: "状态",
    author: "KSW",
    tag: ["状态", "空", "图标"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.986Z",
  },
  {
    id: 267,
    name: "status-info",
    alias: [],
    componentName: "IconStatusInfo",
    componentAlias: [],
    title: "状态信息",
    category: "Information",
    categoryCN: "信息",
    author: "KSW",
    tag: ["状态", "信息", "图标"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.987Z",
  },
  {
    id: 268,
    name: "status-success",
    alias: [],
    componentName: "IconStatusSuccess",
    componentAlias: [],
    title: "状态成功",
    category: "Status",
    categoryCN: "状态指示器",
    author: "KSW",
    tag: ["成功", "完成", "确认", "勾选"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.987Z",
  },
  {
    id: 269,
    name: "status-warning",
    alias: [],
    componentName: "IconStatusWarning",
    componentAlias: [],
    title: "状态警告",
    category: "Alerts",
    categoryCN: "警告",
    author: "KSW",
    tag: ["警告", "状态", "注意", "错误"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.987Z",
  },
  {
    id: 270,
    name: "Step-Status-Failure",
    alias: [],
    componentName: "IconStepStatusFailure",
    componentAlias: [],
    title: "步骤状态失败",
    category: "Process",
    categoryCN: "流程状态",
    author: "KSW",
    tag: ["步骤", "状态", "失败", "流程", "图标"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.930Z",
  },
  {
    id: 271,
    name: "Step-Status-Success",
    alias: [],
    componentName: "IconStepStatusSuccess",
    componentAlias: [],
    title: "步骤状态成功",
    category: "Progress",
    categoryCN: "进度指示器",
    author: "KSW",
    tag: ["步骤", "状态", "成功", "完成", "进度"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.930Z",
  },
  {
    id: 272,
    name: "store-color",
    alias: [],
    componentName: "IconStoreColor",
    componentAlias: [],
    title: "商店颜色",
    category: "Shopping",
    categoryCN: "购物",
    author: "KSW",
    tag: ["商店", "颜色", "购物"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.987Z",
  },
  {
    id: 273,
    name: "subtask",
    alias: [],
    componentName: "IconSubtask",
    componentAlias: [],
    title: "",
    category: "Other",
    categoryCN: "其他",
    author: "KSW",
    tag: [],
    projectName: "base",
    modifiedTime: "2024-12-03T07:57:46.000Z",
  },
  {
    id: 274,
    name: "SupportCenter",
    alias: [],
    componentName: "IconSupportCenter",
    componentAlias: [],
    title: "支持中心",
    category: "Customer",
    categoryCN: "客户服务",
    author: "KSW",
    tag: ["帮助", "支持", "客服", "问题解答"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.931Z",
  },
  {
    id: 275,
    name: "SystemType-aix-color",
    alias: [],
    componentName: "IconSystemTypeAixColor",
    componentAlias: [],
    title: "系统类型",
    category: "Operating",
    categoryCN: "操作系统",
    author: "KSW",
    tag: ["AIX", "系统", "彩色", "图标"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.931Z",
  },
  {
    id: 276,
    name: "SystemType-android-color",
    alias: [],
    componentName: "IconSystemTypeAndroidColor",
    componentAlias: [],
    title: "系统类型",
    category: "System",
    categoryCN: "系统",
    author: "KSW",
    tag: ["系统", "安卓", "颜色"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.932Z",
  },
  {
    id: 277,
    name: "SystemType-arm-color",
    alias: [],
    componentName: "IconSystemTypeArmColor",
    componentAlias: [],
    title: "系统类型",
    category: "System",
    categoryCN: "系统",
    author: "KSW",
    tag: ["系统", "ARM", "彩色"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.932Z",
  },
  {
    id: 278,
    name: "SystemType-AS-color",
    alias: [],
    componentName: "IconSystemTypeASColor",
    componentAlias: [],
    title: "系统类型",
    category: "System",
    categoryCN: "系统组件",
    author: "KSW",
    tag: ["系统", "类型", "彩色"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.931Z",
  },
  {
    id: 279,
    name: "SystemType-firewall-color",
    alias: [],
    componentName: "IconSystemTypeFirewallColor",
    componentAlias: [],
    title: "系统类型",
    category: "System",
    categoryCN: "系统组件",
    author: "KSW",
    tag: ["系统", "防火墙", "颜色"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.932Z",
  },
  {
    id: 280,
    name: "SystemType-interchanger-color",
    alias: [],
    componentName: "IconSystemTypeInterchangerColor",
    componentAlias: [],
    title: "",
    category: "Other",
    categoryCN: "其他",
    author: "KSW",
    tag: [],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.932Z",
  },
  {
    id: 281,
    name: "SystemType-ios-color",
    alias: [],
    componentName: "IconSystemTypeIosColor",
    componentAlias: [],
    title: "系统类型",
    category: "Operating",
    categoryCN: "操作系统",
    author: "KSW",
    tag: ["系统", "iOS", "彩色"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.932Z",
  },
  {
    id: 282,
    name: "SystemType-LB-color",
    alias: [],
    componentName: "IconSystemTypeLBColor",
    componentAlias: [],
    title: "系统类型",
    category: "System",
    categoryCN: "系统组件",
    author: "KSW",
    tag: ["系统", "负载均衡", "彩色"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.931Z",
  },
  {
    id: 283,
    name: "SystemType-linux-color",
    alias: [],
    componentName: "IconSystemTypeLinuxColor",
    componentAlias: [],
    title: "Linux系统类型",
    category: "Operating",
    categoryCN: "操作系统",
    author: "KSW",
    tag: ["Linux", "系统", "图标"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.933Z",
  },
  {
    id: 284,
    name: "SystemType-router-color",
    alias: [],
    componentName: "IconSystemTypeRouterColor",
    componentAlias: [],
    title: "系统类型",
    category: "Networking",
    categoryCN: "网络",
    author: "KSW",
    tag: ["路由器", "网络设备", "无线", "连接"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.933Z",
  },
  {
    id: 285,
    name: "SystemType-Unix-color",
    alias: [],
    componentName: "IconSystemTypeUnixColor",
    componentAlias: [],
    title: "Unix系统类型",
    category: "Operating",
    categoryCN: "操作系统",
    author: "KSW",
    tag: ["Unix", "操作系统", "彩色图标"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.931Z",
  },
  {
    id: 286,
    name: "SystemType-windows-color",
    alias: [],
    componentName: "IconSystemTypeWindowsColor",
    componentAlias: [],
    title: "系统类型",
    category: "Operating",
    categoryCN: "操作系统",
    author: "KSW",
    tag: ["系统", "Windows", "颜色"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.933Z",
  },
  {
    id: 287,
    name: "table-control-more",
    alias: [],
    componentName: "IconTableControlMore",
    componentAlias: [],
    title: "表格控制更多",
    category: "Table",
    categoryCN: "表格控件",
    author: "KSW",
    tag: ["表格", "控制", "更多选项"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.987Z",
  },
  {
    id: 288,
    name: "table-sort-down-color",
    alias: [],
    componentName: "IconTableSortDownColor",
    componentAlias: [],
    title: "表格排序向下颜色",
    category: "Data",
    categoryCN: "数据管理",
    author: "KSW",
    tag: ["表格", "排序", "向下", "颜色"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.987Z",
  },
  {
    id: 289,
    name: "table-sort-normal-color",
    alias: [],
    componentName: "IconTableSortNormalColor",
    componentAlias: [],
    title: "表格排序",
    category: "Data",
    categoryCN: "数据管理",
    author: "KSW",
    tag: ["表格", "排序", "颜色"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.987Z",
  },
  {
    id: 290,
    name: "table-sort-up-color",
    alias: [],
    componentName: "IconTableSortUpColor",
    componentAlias: [],
    title: "表格排序上升颜色",
    category: "Data",
    categoryCN: "数据管理",
    author: "KSW",
    tag: ["表格", "排序", "上升", "颜色"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.988Z",
  },
  {
    id: 291,
    name: "task",
    alias: [],
    componentName: "IconTask",
    componentAlias: [],
    title: "任务",
    category: "Productivity",
    categoryCN: "生产力",
    author: "KSW",
    tag: ["任务管理", "待办事项", "工作效率"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.988Z",
  },
  {
    id: 292,
    name: "test-color",
    alias: [],
    componentName: "IconTestColor",
    componentAlias: [],
    title: "测试颜色",
    category: "Color",
    categoryCN: "颜色",
    author: "KSW",
    tag: ["颜色", "测试", "图标"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.988Z",
  },
  {
    id: 293,
    name: "time",
    alias: [],
    componentName: "IconTime",
    componentAlias: [],
    title: "时间",
    category: "Clock",
    categoryCN: "时钟",
    author: "KSW",
    tag: ["时间", "时钟", "计时"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.988Z",
  },
  {
    id: 294,
    name: "tips",
    alias: [],
    componentName: "IconTips",
    componentAlias: [],
    title: "提示",
    category: "Helpful",
    categoryCN: "帮助资源",
    author: "KSW",
    tag: ["建议", "技巧", "帮助", "指南"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.988Z",
  },
  {
    id: 295,
    name: "top1-color",
    alias: [],
    componentName: "IconTop1Color",
    componentAlias: [],
    title: "第一名颜色",
    category: "Achievement",
    categoryCN: "成就",
    author: "KSW",
    tag: ["第一名", "奖牌", "荣誉"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.989Z",
  },
  {
    id: 296,
    name: "top2-color",
    alias: [],
    componentName: "IconTop2Color",
    componentAlias: [],
    title: "顶部2号彩色",
    category: "Icons",
    categoryCN: "图标",
    author: "KSW",
    tag: ["顶部", "数字", "彩色", "图标"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.989Z",
  },
  {
    id: 297,
    name: "top3-color",
    alias: [],
    componentName: "IconTop3Color",
    componentAlias: [],
    title: "前三名颜色",
    category: "Achievement",
    categoryCN: "成就",
    author: "KSW",
    tag: ["排名", "前三名", "颜色"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.989Z",
  },
  {
    id: 298,
    name: "triangle-bottom",
    alias: [],
    componentName: "IconTriangleBottom",
    componentAlias: [],
    title: "底部三角形",
    category: "Shapes",
    categoryCN: "形状",
    author: "KSW",
    tag: ["三角形", "底部", "几何形状"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.990Z",
  },
  {
    id: 299,
    name: "triangle-top",
    alias: [],
    componentName: "IconTriangleTop",
    componentAlias: [],
    title: "三角形顶部",
    category: "Shapes",
    categoryCN: "形状",
    author: "KSW",
    tag: ["几何", "图形", "三角形"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.990Z",
  },
  {
    id: 300,
    name: "unfold",
    alias: [],
    componentName: "IconUnfold",
    componentAlias: [],
    title: "展开",
    category: "Navigation",
    categoryCN: "导航",
    author: "KSW",
    tag: ["展开", "箭头", "方向"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.990Z",
  },
  {
    id: 301,
    name: "upload",
    alias: [],
    componentName: "IconUpload",
    componentAlias: [],
    title: "上传",
    category: "File",
    categoryCN: "文件管理",
    author: "KSW",
    tag: ["上传", "文件", "数据传输"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.990Z",
  },
  {
    id: 302,
    name: "user-filled",
    alias: [],
    componentName: "IconUserFilled",
    componentAlias: [],
    title: "用户-填充",
    category: "User",
    categoryCN: "用户",
    author: "KSW",
    tag: ["用户", "人们"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.990Z",
  },
  {
    id: 303,
    name: "users-filled",
    alias: [],
    componentName: "IconUsersFilled",
    componentAlias: [],
    title: "用户们-填充",
    category: "User",
    categoryCN: "用户",
    author: "KSW",
    tag: ["用户们", "人们"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.991Z",
  },
  {
    id: 304,
    name: "users",
    alias: [],
    componentName: "IconUsers",
    componentAlias: [],
    title: "用户们",
    category: "User",
    categoryCN: "用户",
    author: "KSW",
    tag: ["用户们", "人们"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.991Z",
  },
  {
    id: 305,
    name: "variable",
    alias: [],
    componentName: "IconVariable",
    componentAlias: [],
    title: "变量",
    category: "Programming",
    categoryCN: "编程",
    author: "KSW",
    tag: ["变量", "编程", "数据存储"],
    projectName: "base",
    modifiedTime: "2024-11-29T03:39:52.274Z",
  },
  {
    id: 306,
    name: "version-color",
    alias: [],
    componentName: "IconVersionColor",
    componentAlias: [],
    title: "",
    category: "Other",
    categoryCN: "其他",
    author: "KSW",
    tag: [],
    projectName: "base",
    modifiedTime: "2024-12-03T06:25:36.000Z",
  },
  {
    id: 307,
    name: "video-color",
    alias: [],
    componentName: "IconVideoColor",
    componentAlias: [],
    title: "视频-颜色",
    category: "Other",
    categoryCN: "其他",
    author: "KSW",
    tag: [],
    projectName: "base",
    modifiedTime: "2025-02-10T09:37:50.000Z",
  },
  {
    id: 308,
    name: "video",
    alias: [],
    componentName: "IconVideo",
    componentAlias: [],
    title: "视频",
    category: "Other",
    categoryCN: "其他",
    author: "KSW",
    tag: [],
    projectName: "base",
    modifiedTime: "2025-02-10T09:37:50.000Z",
  },
  {
    id: 309,
    name: "view-switch-card",
    alias: [],
    componentName: "IconViewSwitchCard",
    componentAlias: [],
    title: "视图切换卡",
    category: "UI",
    categoryCN: "用户界面组件",
    author: "KSW",
    tag: ["视图", "切换", "卡片", "用户界面"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.991Z",
  },
  {
    id: 310,
    name: "view-switch-color",
    alias: [],
    componentName: "IconViewSwitchColor",
    componentAlias: [],
    title: "视图切换颜色",
    category: "UI",
    categoryCN: "用户界面元素",
    author: "KSW",
    tag: ["视图", "切换", "颜色"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.991Z",
  },
  {
    id: 311,
    name: "view-toggle-details",
    alias: [],
    componentName: "IconViewToggleDetails",
    componentAlias: [],
    title: "视图切换详情",
    category: "UI",
    categoryCN: "用户界面元素",
    author: "KSW",
    tag: ["视图", "切换", "详情", "用户界面"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.991Z",
  },
  {
    id: 312,
    name: "view-toggle-table",
    alias: [],
    componentName: "IconViewToggleTable",
    componentAlias: [],
    title: "视图切换表格",
    category: "UI",
    categoryCN: "用户界面元素",
    author: "KSW",
    tag: ["视图", "切换", "表格", "UI", "交互"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.991Z",
  },
  {
    id: 313,
    name: "warning",
    alias: [],
    componentName: "IconWarning",
    componentAlias: [],
    title: "警告",
    category: "Safety",
    categoryCN: "安全",
    author: "KSW",
    tag: ["警告", "注意", "危险"],
    projectName: "base",
    modifiedTime: "2024-11-07T03:44:01.992Z",
  },
];
