export const iconsDataKAPA = [
  {
    id: 0,
    name: "apa-component",
    alias: [],
    componentName: "IconApaComponent",
    componentAlias: [],
    title: "",
    category: "KAPA",
    categoryCN: "KAPA",
    author: "KSW",
    tag: [],
    projectName: "KAPA",
    modifiedTime: "2025-07-24T06:11:16.527Z",
  },
  {
    id: 1,
    name: "apa-down",
    alias: [],
    componentName: "IconApaDown",
    componentAlias: [],
    title: "",
    category: "KAPA",
    categoryCN: "KAPA",
    author: "KSW",
    tag: [],
    projectName: "KAPA",
    modifiedTime: "2025-07-29T02:40:29.000Z",
  },
  {
    id: 2,
    name: "apa-grip-vertical",
    alias: [],
    componentName: "IconApaGripVertical",
    componentAlias: [],
    title: "",
    category: "KAPA",
    categoryCN: "KAPA",
    author: "KSW",
    tag: [],
    projectName: "KAPA",
    modifiedTime: "2025-07-29T02:38:37.000Z",
  },
  {
    id: 3,
    name: "apa-process",
    alias: [],
    componentName: "IconApaProcess",
    componentAlias: [],
    title: "",
    category: "KAPA",
    categoryCN: "KAPA",
    author: "KSW",
    tag: [],
    projectName: "KAPA",
    modifiedTime: "2025-07-24T06:11:16.528Z",
  },
  {
    id: 4,
    name: "apa-tool",
    alias: [],
    componentName: "IconApaTool",
    componentAlias: [],
    title: "",
    category: "KAPA",
    categoryCN: "KAPA",
    author: "KSW",
    tag: [],
    projectName: "KAPA",
    modifiedTime: "2025-07-24T06:11:16.533Z",
  },
];
