name: icon-automation
on:
  push:
    branches:
    - master
    # file paths to consider in the event. Optional; defaults to all.
    paths:
      - package.json

jobs:
  icon_automation:
    name: icon automation
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v3
      with:
        node-version: '20'
    - run: yarn install
    - run: yarn generate
    - run: yarn build
    - run: yarn build-bundle
    
    - name: Deploy GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: dist
        ssh-key: ${{ secrets.GH_TOKEN }}
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    
    - name: Publish NPM
      uses: JS-DevTools/npm-publish@v3
      with:
        token: ${{ secrets.NPM_TOKEN }}